package editor

//nolint:gochecknoglobals // package-level dispatch map for O(1) command routing
var staticHandlers map[string]commandHandler

//nolint:gochecknoinits // required to break the init cycle: handleBatchExecute → commandHandlerFor → staticHandlers
func init() {
	staticHandlers = map[string]commandHandler{
	// Slides basic
	OpBatchExecute:       handleBatchExecute,
	OpSlideCount:         handleSlideCount,
	OpAddSlide:           handleAddSlide,
	OpRemoveSlide:        handleRemoveSlide,
	OpMoveSlide:          handleMoveSlide,
	OpDuplicateSlide:     handleDuplicateSlide,
	OpDuplicateSlideAfter: handleDuplicateSlideAfter,
	OpListSlides:         handleListSlides,
	OpSetSlideTitle:      handleSetSlideTitle,
	OpUpdateSlide:        handleUpdateSlide,
	OpValidate:           handleValidate,
	OpRepair:             handleRepair,

	// Layout & metadata
	OpGetMetadata:             handleGetMetadata,
	OpListSlideCharts:         handleListSlideCharts,
	OpUpdateChartData:         handleUpdateChartData,
	OpUpdateChartDataBatch:    handleUpdateChartDataBatch,
	OpUpdateChartFormatting:   handleUpdateChartFormatting,
	OpGetChartState:           handleGetChartState,
	OpAddChart:                handleAddChart,
	OpGetSlideLayoutRef:       handleGetSlideLayoutRef,
	OpListSlideLayouts:        handleListSlideLayouts,
	OpListSlideMasters:        handleListSlideMasters,
	OpListMasterLayouts:       handleListMasterLayouts,
	OpRebindSlideLayout:       handleRebindSlideLayout,
	OpCloneLayoutMasterFamily: handleCloneLayoutMasterFamily,
	OpAddSlideMaster:          handleAddSlideMaster,
	OpRemoveSlideMaster:       handleRemoveSlideMaster,
	OpAddSlideLayout:          handleAddSlideLayout,
	OpRemoveSlideLayout:       handleRemoveSlideLayout,
	OpApplyTheme:              handleApplyTheme,
	OpSetSlideSize:            handleSetSlideSize,
	OpMergeFromFile:           handleMergeFromFile,
	OpGetCoreProperties:       handleGetCoreProperties,
	OpSetCoreProperties:       handleSetCoreProperties,
	OpListPlaceholders:        handleListPlaceholders,
	OpSetPlaceholderContent:   handleSetPlaceholderContent,

	// Theme & layout shapes
	OpGetLayoutShapes:       handleGetLayoutShapes,
	OpGetMasterShapes:       handleGetMasterShapes,
	OpGetLayoutPlaceholders: handleGetLayoutPlaceholders,
	OpGetMasterPlaceholders: handleGetMasterPlaceholders,
	OpSetGlobalThemePreset:  handleSetGlobalThemePreset,
	OpSetThemeFontScheme:    handleSetThemeFontScheme,
	OpSetThemeColorScheme:   handleSetThemeColorScheme,
	OpGetThemeInventory:     handleGetThemeInventory,

	// Content & sections
	OpAddSection:         handleAddSection,
	OpRemoveSection:      handleRemoveSection,
	OpRenameSection:      handleRenameSection,
	OpGetSections:        handleGetSections,
	OpFindAndReplace:     handleFindAndReplace,
	OpSearchShapes:       handleSearchShapes,
	OpSetModifyPassword:  handleSetModifyPassword,
	OpSetMarkAsFinal:     handleSetMarkAsFinal,
	OpAddCustomXML:       handleAddCustomXML,
	OpListCustomXML:      handleListCustomXML,
	OpRemoveCustomXML:    handleRemoveCustomXML,
	OpAddVba:             handleAddVba,
	OpMarkdownToSlides:   handleMarkdownToSlides,
	OpURLFetchToSlides:   handleURLFetchToSlides,
	OpAddMermaidShape:    handleAddMermaidShape,
	OpAddSmartArt:        handleAddSmartArt,
	OpUpdateSmartArt:     handleUpdateSmartArt,
	OpSetSlideBackground: handleSetSlideBackground,
	OpSetSlideHeaderFooter: handleSetSlideHeaderFooter,
	OpAddAnimation:       handleAddAnimation,
	OpSetSlideTransition: handleSetSlideTransition,
	OpMergeFromEditor:    handleMergeFromEditor,

	// Comments & shapes (read)
	OpGetAuthors:          handleGetAuthors,
	OpAddAuthor:           handleAddAuthor,
	OpGetComments:         handleGetComments,
	OpAddComment:          handleAddComment,
	OpRemoveComment:       handleRemoveComment,
	OpListShapes:          handleListShapes,
	OpGetSlideTextStates:  handleGetSlideTextStates,
	OpGetShapeTextState:   handleGetShapeTextState,
	OpGetShapeRuns:        handleGetShapeRuns,
	OpSetShapeRuns:        handleSetShapeRuns,
	OpSetSlideShapeRuns:   handleSetSlideShapeRuns,
	OpUpdateDeckRunTexts:  handleUpdateDeckRunTexts,
	OpUpdateSlideRunTexts: handleUpdateSlideRunTexts,
	OpUpdateShapeRunText:  handleUpdateShapeRunText,
	OpAppendShapeRun:      handleAppendShapeRun,

	// Shape mutations
	OpAddShape:          handleAddShape,
	OpAddTextbox:        handleAddTextbox,
	OpAddTextboxes:      handleAddTextboxes,
	OpAddConnectors:     handleAddConnectors,
	OpReserveShapeIDs:   handleReserveShapeIDs,
	OpAddConnector:      handleAddConnector,
	OpAddGroupShape:     handleAddGroupShape,
	OpBuildFreeform:     handleBuildFreeform,
	OpAddImage:          handleAddImage,
	OpRemoveShape:       handleRemoveShape,
	OpGroupShapes:       handleGroupShapes,
	OpUngroupShapes:     handleUngroupShapes,
	OpUpdateShape:       handleUpdateShape,
	OpMoveShapeToFront:  handleMoveShapeToFront,
	OpMoveShapeToBack:   handleMoveShapeToBack,
	OpMoveShapeToIndex:  handleMoveShapeToIndex,
	OpGetImageMetadata:  handleGetImageMetadata,
	OpAddVideo:          handleAddVideo,
	OpAddAudio:          handleAddAudio,
	OpAddOLEObject:      handleAddOLEObject,
	OpListSlideImages:   handleListSlideImages,
	OpSwapImageByIndex:  handleSwapImageByIndex,
	OpSwapImageByRelID:  handleSwapImageByRelID,

	// Notes & tables
	OpGetNotes:              handleGetNotes,
	OpNotesSlideExists:      handleNotesSlideExists,
	OpSetNotes:              handleSetNotes,
	OpSetNotesShapeText:     handleSetNotesShapeText,
	OpSetNotesShapeProps:    handleSetNotesShapeProps,
	OpAddTable:              handleAddTable,
	OpGetTable:              handleGetTable,
	OpMergeTableCells:       handleMergeTableCells,
	OpSplitTableCell:        handleSplitTableCell,
	OpUpdateTableFlags:      handleUpdateTableFlags,
	OpUpdateTableCell:       handleUpdateTableCell,
	OpSetTableStyle:         handleSetTableStyle,
	OpDefineTableStyle:      handleDefineTableStyle,
	OpListTableStyles:       handleListTableStyles,
	OpSetTableRowHeight:     handleSetTableRowHeight,
	OpSetTableColumnWidth:   handleSetTableColumnWidth,
	OpListNotesShapes:       handleListNotesShapes,
	OpListNotesPlaceholders: handleListNotesPlaceholders,
	OpUpdateNotesMaster:     handleUpdateNotesMaster,

	// Handout master & digital signature
	OpGetHandoutMaster:    handleGetHandoutMaster,
	OpUpdateHandoutMaster: handleUpdateHandoutMaster,
	OpHasDigitalSignature: handleHasDigitalSignature,
	}
}
