package editor

// supportedContentOps returns ops for shapes, text, tables, notes, media, and export.
func supportedContentOps() []string {
	return append([]string{
		OpFindAndReplace,
		OpSearchShapes,
		OpGetAuthors,
		OpAddAuthor,
		OpGetComments,
		OpAddComment,
		OpRemoveComment,
		OpListShapes,
		OpGetSlideTextStates,
		OpGetShapeTextState,
		OpGetEffectiveShapeStyle,
		OpGetShapeRuns,
		OpSetShapeRuns,
		OpSetSlideShapeRuns,
		OpUpdateDeckRunTexts,
		OpUpdateSlideRunTexts,
		OpUpdateShapeRunText,
		OpAppendShapeRun,
		OpAddShape,
		OpAddTextbox,
		OpAddTextboxes,
		OpAddConnectors,
		OpReserveShapeIDs,
		OpAddConnector,
		OpAddGroupShape,
		OpGroupShapes,
		OpUngroupShapes,
		OpBuildFreeform,
		OpAddImage,
		OpRemoveShape,
		OpClearShapes,
		OpUpdateShape,
		OpMoveShapeToFront,
		OpMoveShapeToBack,
		OpGetNotes,
		OpNotesSlideExists,
		OpSetNotes,
		OpSetNotesShapeText,
		OpSetNotesShapeProps,
		OpSetModifyPassword,
		OpSetMarkAsFinal,
		OpAddTable,
		OpGetTable,
		OpMergeTableCells,
		OpSplitTableCell,
		OpUpdateTableFlags,
		OpUpdateTableCell,
		OpSetTableStyle,
		OpDefineTableStyle,
		OpListTableStyles,
		OpSetTableRowHeight,
		OpSetTableColumnWidth,
		OpAddTableRow,
		OpAddTableColumn,
		OpInsertTableRow,
		OpRemoveTableRow,
		OpInsertTableColumn,
		OpRemoveTableColumn,
		OpUpdateTableCellBorder,
		OpAddCustomXML,
		OpListCustomXML,
		OpRemoveCustomXML,
		OpAddVba,
		OpExportPDF,
		OpExportHTML,
		OpListPlaceholders,
		OpSetPlaceholderContent,
		OpGetImageMetadata,
		OpAddVideo,
		OpAddOnlineVideo,
		OpAddAudio,
		OpAddOLEObject,
		OpMarkdownToSlides,
		OpURLFetchToSlides,
		OpAddMermaidShape,
		OpAddSmartArt,
		OpAddAnimation,
		OpSetSlideTransition,
		OpMoveShapeToIndex,
	}, contentMediaAndStructureOps()...)
}

// contentMediaAndStructureOps returns the media, notes, SmartArt, background and
// export half of the content ops, split out to keep each function readable.
func contentMediaAndStructureOps() []string {
	return []string{
		OpListSlideImages,
		OpListSlideMedia,
		OpExtractMedia,
		OpSwapImageByIndex,
		OpSwapImageByRelID,
		OpListNotesShapes,
		OpListNotesPlaceholders,
		OpUpdateNotesMaster,
		OpMergeFromEditor,
		OpUpdateSmartArt,
		OpDeleteSmartArt,
		OpChangeSmartArtLayout,
		OpSetSmartArtStyle,
		OpSetSmartArtNodes,
		OpSetSlideBackground,
		OpSetSlideHeaderFooter,
		OpGetSlideHeaderFooter,
		OpGetHandoutMaster,
		OpUpdateHandoutMaster,
		OpIsDigitallySigned,
	}
}
