repos:
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go
        language: system
        pass_filenames: false
        args: ["vet", "./cmd/...", "./internal/...", "./pkg/..."]

      - id: golangci-lint
        name: golangci-lint
        pass_filenames: false
        args:
          ["run", "--config", ".golangci.yml", "./cmd/...", "./internal/...", "./pkg/..."]

      - id: go-mod-tidy
        name: go mod tidy
        entry: go
        language: system
        pass_filenames: false
        args: ["mod", "tidy"]

      - id: go-test
        name: go test
        entry: go
        language: system
        pass_filenames: false
        args: ["test", "./cmd/...", "./internal/...", "./pkg/..."]
