SHAPE_RIGHT_TRIANGLE  # unused variable (python\gopptx\constants.py:19)
SHAPE_DIAMOND  # unused variable (python\gopptx\constants.py:20)
SHAPE_PENTAGON  # unused variable (python\gopptx\constants.py:21)
SHAPE_HEXAGON  # unused variable (python\gopptx\constants.py:22)
SHAPE_PARALLELOGRAM  # unused variable (python\gopptx\constants.py:23)
SHAPE_CLOUD  # unused variable (python\gopptx\constants.py:24)
SHAPE_HEART  # unused variable (python\gopptx\constants.py:25)
SHAPE_STAR_5  # unused variable (python\gopptx\constants.py:26)
SHAPE_STAR_6  # unused variable (python\gopptx\constants.py:27)
SHAPE_STAR_7  # unused variable (python\gopptx\constants.py:28)
SHAPE_STAR_8  # unused variable (python\gopptx\constants.py:29)
SHAPE_STAR_10  # unused variable (python\gopptx\constants.py:30)
SHAPE_STAR_12  # unused variable (python\gopptx\constants.py:31)
SHAPE_STAR_16  # unused variable (python\gopptx\constants.py:32)
SHAPE_STAR_24  # unused variable (python\gopptx\constants.py:33)
SHAPE_STAR_32  # unused variable (python\gopptx\constants.py:34)
SHAPE_FLOWCHART_PROCESS  # unused variable (python\gopptx\constants.py:37)
SHAPE_FLOWCHART_DECISION  # unused variable (python\gopptx\constants.py:38)
SHAPE_FLOWCHART_DATA  # unused variable (python\gopptx\constants.py:39)
SHAPE_FLOWCHART_PREDEFINED_PROCESS  # unused variable (python\gopptx\constants.py:40)
SHAPE_FLOWCHART_INTERNAL_STORAGE  # unused variable (python\gopptx\constants.py:41)
SHAPE_FLOWCHART_DOCUMENT  # unused variable (python\gopptx\constants.py:42)
SHAPE_FLOWCHART_MULTIDOCUMENT  # unused variable (python\gopptx\constants.py:43)
SHAPE_FLOWCHART_TERMINATOR  # unused variable (python\gopptx\constants.py:44)
SHAPE_FLOWCHART_PREPARATION  # unused variable (python\gopptx\constants.py:45)
SHAPE_FLOWCHART_MANUAL_INPUT  # unused variable (python\gopptx\constants.py:46)
SHAPE_FLOWCHART_MANUAL_OPERATION  # unused variable (python\gopptx\constants.py:47)
SHAPE_LINE  # unused variable (python\gopptx\constants.py:50)
SHAPE_CURVED_CONNECTOR_2  # unused variable (python\gopptx\constants.py:51)
SHAPE_CURVED_CONNECTOR_3  # unused variable (python\gopptx\constants.py:52)
SHAPE_CURVED_CONNECTOR_4  # unused variable (python\gopptx\constants.py:53)
SHAPE_CURVED_CONNECTOR_5  # unused variable (python\gopptx\constants.py:54)
SHAPE_BENT_CONNECTOR_2  # unused variable (python\gopptx\constants.py:55)
SHAPE_BENT_CONNECTOR_3  # unused variable (python\gopptx\constants.py:56)
SHAPE_BENT_CONNECTOR_4  # unused variable (python\gopptx\constants.py:57)
SHAPE_BENT_CONNECTOR_5  # unused variable (python\gopptx\constants.py:58)
SIZE_4X3_WIDTH  # unused variable (python\gopptx\constants.py:79)
SIZE_4X3_HEIGHT  # unused variable (python\gopptx\constants.py:80)
SIZE_16X9_WIDTH  # unused variable (python\gopptx\constants.py:81)
SIZE_16X9_HEIGHT  # unused variable (python\gopptx\constants.py:82)
SUPPORTED_OPS_SET  # unused variable (python\gopptx\ops.py:111)
_.new  # unused method (python\gopptx\presentation\base.py:79)
exc_val  # unused variable (python\gopptx\presentation\batch.py:57)
exc_tb  # unused variable (python\gopptx\presentation\batch.py:58)
_.results  # unused property (python\gopptx\presentation\batch.py:66)
_.get_authors  # unused method (python\gopptx\presentation\comments_charts.py:25)
_.add_author  # unused method (python\gopptx\presentation\comments_charts.py:30)
_.add_comment  # unused method (python\gopptx\presentation\comments_charts.py:47)
_.remove_comment  # unused method (python\gopptx\presentation\comments_charts.py:72)
_.update_chart_data  # unused method (python\gopptx\presentation\comments_charts.py:150)
_.replace_chart_data_by_index  # unused method (python\gopptx\presentation\comments_charts.py:218)
_.replace_chart_data_by_rel_id  # unused method (python\gopptx\presentation\comments_charts.py:232)
_.slide_master  # unused property (python\gopptx\presentation\master.py:41)
_.get_by_name  # unused method (python\gopptx\presentation\master.py:73)
_.slide_layouts  # unused property (python\gopptx\presentation\master.py:108)
_.batch  # unused method (python\gopptx\presentation\runtime.py:102)
_.save  # unused method (python\gopptx\presentation\runtime.py:229)
exc_val  # unused variable (python\gopptx\presentation\runtime.py:253)
exc_tb  # unused variable (python\gopptx\presentation\runtime.py:254)
_.search_shapes  # unused method (python\gopptx\presentation\shapes_tables.py:40)
_.find_and_replace  # unused method (python\gopptx\presentation\shapes_tables.py:125)
_.rebind_slide_layout  # unused method (python\gopptx\presentation\slides.py:43)
_.clone_layout_master_family  # unused method (python\gopptx\presentation\slides.py:62)
_.apply_theme  # unused method (python\gopptx\presentation\slides.py:81)
_.set_slide_size  # unused method (python\gopptx\presentation\slides.py:93)
_.get_sections  # unused method (python\gopptx\presentation\slides.py:127)
_.add_section  # unused method (python\gopptx\presentation\slides.py:131)
_.remove_section  # unused method (python\gopptx\presentation\slides.py:140)
_.rename_section  # unused method (python\gopptx\presentation\slides.py:148)
_.get_core_properties  # unused method (python\gopptx\presentation\slides.py:169)
_.set_core_properties  # unused method (python\gopptx\presentation\slides.py:177)
_.set_modify_password  # unused method (python\gopptx\presentation\slides.py:196)
_.set_mark_as_final  # unused method (python\gopptx\presentation\slides.py:204)
_.slide_masters  # unused property (python\gopptx\presentation\slides.py:230)
_.move_slide  # unused method (python\gopptx\presentation\slides.py:269)
_.merge_from_file  # unused method (python\gopptx\presentation\slides.py:312)
_.add_title_slide  # unused method (python\gopptx\presentation\slides.py:321)
_.add_bullet_slide  # unused method (python\gopptx\presentation\slides.py:332)
size  # unused variable (python\gopptx\schemas.py:23)
subject  # unused variable (python\gopptx\schemas.py:30)
creator  # unused variable (python\gopptx\schemas.py:31)
keywords  # unused variable (python\gopptx\schemas.py:32)
description  # unused variable (python\gopptx\schemas.py:33)
lastModifiedBy  # unused variable (python\gopptx\schemas.py:34)
revision  # unused variable (python\gopptx\schemas.py:35)
created  # unused variable (python\gopptx\schemas.py:36)
modified  # unused variable (python\gopptx\schemas.py:37)
category  # unused variable (python\gopptx\schemas.py:38)
contentStatus  # unused variable (python\gopptx\schemas.py:39)
ID  # unused variable (python\gopptx\schemas.py:61)
Name  # unused variable (python\gopptx\schemas.py:62)
Type  # unused variable (python\gopptx\schemas.py:63)
Text  # unused variable (python\gopptx\schemas.py:64)
X  # unused variable (python\gopptx\schemas.py:65)
Y  # unused variable (python\gopptx\schemas.py:66)
W  # unused variable (python\gopptx\schemas.py:67)
H  # unused variable (python\gopptx\schemas.py:68)
x_values  # unused variable (python\gopptx\schemas.py:84)
y_values  # unused variable (python\gopptx\schemas.py:85)
sizes  # unused variable (python\gopptx\schemas.py:86)
Index  # unused variable (python\gopptx\schemas.py:99)
RelID  # unused variable (python\gopptx\schemas.py:100)
ChartPart  # unused variable (python\gopptx\schemas.py:101)
Part  # unused variable (python\gopptx\schemas.py:107)
Name  # unused variable (python\gopptx\schemas.py:108)
MasterPart  # unused variable (python\gopptx\schemas.py:109)
MasterPart  # unused variable (python\gopptx\schemas.py:115)
ThemePart  # unused variable (python\gopptx\schemas.py:116)
LayoutMap  # unused variable (python\gopptx\schemas.py:117)
Index  # unused variable (python\gopptx\schemas.py:123)
SlideID  # unused variable (python\gopptx\schemas.py:124)
RelationshipID  # unused variable (python\gopptx\schemas.py:125)
PartName  # unused variable (python\gopptx\schemas.py:126)
Title  # unused variable (python\gopptx\schemas.py:127)
Name  # unused variable (python\gopptx\schemas.py:133)
GUID  # unused variable (python\gopptx\schemas.py:134)
SlideIDs  # unused variable (python\gopptx\schemas.py:135)
name_contains  # unused variable (python\gopptx\schemas.py:141)
type_equals  # unused variable (python\gopptx\schemas.py:142)
text_contains  # unused variable (python\gopptx\schemas.py:143)
case_sensitive  # unused variable (python\gopptx\schemas.py:144)
SlideIndex  # unused variable (python\gopptx\schemas.py:150)
ID  # unused variable (python\gopptx\schemas.py:157)
Name  # unused variable (python\gopptx\schemas.py:158)
Initials  # unused variable (python\gopptx\schemas.py:159)
LastIndex  # unused variable (python\gopptx\schemas.py:160)
AuthorID  # unused variable (python\gopptx\schemas.py:166)
Text  # unused variable (python\gopptx\schemas.py:167)
Created  # unused variable (python\gopptx\schemas.py:168)
X  # unused variable (python\gopptx\schemas.py:169)
Y  # unused variable (python\gopptx\schemas.py:170)
Index  # unused variable (python\gopptx\schemas.py:171)
request_id  # unused variable (python\gopptx\schemas.py:179)
details  # unused variable (python\gopptx\schemas.py:187)
ok  # unused variable (python\gopptx\schemas.py:193)
request_id  # unused variable (python\gopptx\schemas.py:195)
row_span  # unused variable (python\gopptx\schemas.py:205)
col_span  # unused variable (python\gopptx\schemas.py:206)
v_merge  # unused variable (python\gopptx\schemas.py:207)
h_merge  # unused variable (python\gopptx\schemas.py:208)
is_merge_origin  # unused variable (python\gopptx\schemas.py:209)
is_spanned  # unused variable (python\gopptx\schemas.py:210)
first_row  # unused variable (python\gopptx\schemas.py:219)
first_col  # unused variable (python\gopptx\schemas.py:220)
last_row  # unused variable (python\gopptx\schemas.py:221)
last_col  # unused variable (python\gopptx\schemas.py:222)
band_row  # unused variable (python\gopptx\schemas.py:223)
band_col  # unused variable (python\gopptx\schemas.py:224)
_.list_charts  # unused method (python\gopptx\slide\slide.py:115)
_.remove  # unused method (python\gopptx\slide\slide.py:204)
_.duplicate  # unused method (python\gopptx\slide\slide.py:208)
_.is_merge_origin  # unused property (python\gopptx\slide\table.py:30)
_.is_spanned  # unused property (python\gopptx\slide\table.py:38)
_.row_span  # unused property (python\gopptx\slide\table.py:46)
_.col_span  # unused property (python\gopptx\slide\table.py:55)
_.split  # unused method (python\gopptx\slide\table.py:73)
_.merge  # unused method (python\gopptx\slide\table.py:114)
_.iter_cells  # unused method (python\gopptx\slide\table.py:294)

# Additional python/gopptx public API and TypedDict fields referenced dynamically.
_.add_vba_project  # unused method (python\gopptx\presentation\vba.py:17)
Emu  # unused variable (python\gopptx\schemas.py:26)
Inches  # unused variable (python\gopptx\schemas.py:27)
Point  # unused variable (python\gopptx\schemas.py:28)
RGBColor  # unused variable (python\gopptx\schemas.py:31)
lastPrinted  # unused variable (python\gopptx\schemas.py:65)
solid  # unused variable (python\gopptx\schemas.py:95)
background  # unused variable (python\gopptx\schemas.py:96)
gradient  # unused variable (python\gopptx\schemas.py:97)
pattern  # unused variable (python\gopptx\schemas.py:98)
position_pct  # unused variable (python\gopptx\schemas.py:104)
angle_deg  # unused variable (python\gopptx\schemas.py:111)
stops  # unused variable (python\gopptx\schemas.py:112)
preset  # unused variable (python\gopptx\schemas.py:118)
fg_color  # unused variable (python\gopptx\schemas.py:119)
bg_color  # unused variable (python\gopptx\schemas.py:120)
width_emu  # unused variable (python\gopptx\schemas.py:127)
dash_style  # unused variable (python\gopptx\schemas.py:128)
inherit  # unused variable (python\gopptx\schemas.py:134)
blur_emu  # unused variable (python\gopptx\schemas.py:136)
distance_emu  # unused variable (python\gopptx\schemas.py:137)
radius_emu  # unused variable (python\gopptx\schemas.py:145)
fill  # unused variable (python\gopptx\schemas.py:173)
line  # unused variable (python\gopptx\schemas.py:174)
shadow  # unused variable (python\gopptx\schemas.py:175)
glow  # unused variable (python\gopptx\schemas.py:176)
blur  # unused variable (python\gopptx\schemas.py:177)
soft_edge  # unused variable (python\gopptx\schemas.py:178)
reflection  # unused variable (python\gopptx\schemas.py:179)
click_action  # unused variable (python\gopptx\schemas.py:254)
format  # unused variable (python\gopptx\schemas.py:193)
hash  # unused variable (python\gopptx\schemas.py:194)
right  # unused variable (python\gopptx\schemas.py:201)
bottom  # unused variable (python\gopptx\schemas.py:203)
_.add_line_to  # unused method (python\gopptx\slide\freeform_builder.py:43)
_.add_line_segments  # unused method (python\gopptx\slide\freeform_builder.py:48)
_.move_to  # unused method (python\gopptx\slide\freeform_builder.py:53)
_.convert_to_shape  # unused method (python\gopptx\slide\freeform_builder.py:60)
_.insert_text  # unused method (python\gopptx\slide\placeholder.py:63)
_.insert_picture  # unused method (python\gopptx\slide\placeholder.py:86)
_.insert_table  # unused method (python\gopptx\slide\placeholder.py:107)
_.insert_chart  # unused method (python\gopptx\slide\placeholder.py:128)
_.get_placeholder  # unused method (python\gopptx\slide\placeholder_mixin.py:27)
_.notes_slide  # unused property (python\gopptx\slide\slide.py:206)
_.apply_style  # unused method (python\gopptx\slide\table.py:270)
_.span_height  # unused property (python\gopptx\slide\table_cells.py:58)
_.span_width  # unused property (python\gopptx\slide\table_cells.py:63)
_.update_chart_formatting_by_rel_id  # unused method (python\gopptx\presentation\comments_charts.py)

# TypedDict/public API symbols moved during modular split.
show_title  # unused variable (python\gopptx\schemas_chart_layout.py)
title_overlay  # unused variable (python\gopptx\schemas_chart_layout.py)
plot_visible_only  # unused variable (python\gopptx\schemas_chart_layout.py)
show_legend  # unused variable (python\gopptx\schemas_chart_layout.py)
legend_position  # unused variable (python\gopptx\schemas_chart_layout.py)
legend_overlay  # unused variable (python\gopptx\schemas_chart_layout.py)
show_data_labels  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_position  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_show_legend_key  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_show_value  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_show_category  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_show_series_name  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_show_percent  # unused variable (python\gopptx\schemas_chart_layout.py)
data_label_show_bubble_size  # unused variable (python\gopptx\schemas_chart_layout.py)
CX  # unused variable (python\gopptx\schemas_chart_layout.py)
CY  # unused variable (python\gopptx\schemas_chart_layout.py)
Shapes  # unused variable (python\gopptx\schemas_chart_layout.py)
Placeholders  # unused variable (python\gopptx\schemas_chart_layout.py)

_.add_category  # unused method (python\gopptx\slide\chart_data.py)
_.add_series  # unused method (python\gopptx\slide\chart_data.py)
_.data_labels  # unused property (python\gopptx\slide\chart_model.py)
_.chart_title  # unused property (python\gopptx\slide\chart_model.py)
_.legend  # unused property (python\gopptx\slide\chart_model.py)
_.plots  # unused property (python\gopptx\slide\chart_model.py)
_.replace_data  # unused method (python\gopptx\slide\chart_model.py)
_.category_axis  # unused property (python\gopptx\slide\chart_model.py)
_.value_axis  # unused property (python\gopptx\slide\chart_model.py)
_.chart_style  # unused property (python\gopptx\slide\chart_model.py)
_.present  # unused property (python\gopptx\slide\chart_model_axis_series.py)
_.major_gridlines_visible  # unused property (python\gopptx\slide\chart_model_axis_series.py)
_.layout_placeholder  # unused property (python\gopptx\slide\placeholder.py)
_.master_placeholder  # unused property (python\gopptx\slide\placeholder.py)
_.add_run  # unused method (python\gopptx\slide\text_model.py)
_paragraph_index  # unused variable (python\gopptx\slide\text_model.py)
_.paragraphs  # unused property (python\gopptx\slide\text_model.py)
_.fit_text  # unused method (python\gopptx\slide\text_model.py)
_.list_charts  # unused method (python\gopptx\slide\slide_mixins.py)
_.get_chart_state_by_rel_id  # unused method (python\gopptx\presentation\chart_state_mixin.py)
_.body_shape  # unused property (python\gopptx\slide\notes_slide.py)
_.notes_text_frame  # unused property (python\gopptx\slide\notes_slide.py)
_.text_frame  # unused property (python\gopptx\slide\notes_slide.py)
_.is_placeholder  # unused property (python\gopptx\slide\notes_slide.py)
_.x  # unused property (python\gopptx\slide\notes_slide.py)
_.y  # unused property (python\gopptx\slide\notes_slide.py)
_.cx  # unused property (python\gopptx\slide\notes_slide.py)
_.cy  # unused property (python\gopptx\slide\notes_slide.py)
_.clear  # unused method (python\gopptx\slide\notes_text_model.py)
_.add_paragraph  # unused method (python\gopptx\slide\notes_text_model.py)
_.add_run  # unused method (python\gopptx\slide\notes_text_model.py)
category_axis_tick_label_pos  # unused variable (python\gopptx\schemas_chart_layout.py)
value_axis_tick_label_pos  # unused variable (python\gopptx\schemas_chart_layout.py)
category_axis_major_gridlines  # unused variable (python\gopptx\schemas_chart_layout.py)
value_axis_major_gridlines  # unused variable (python\gopptx\schemas_chart_layout.py)
category_axis_crosses  # unused variable (python\gopptx\schemas_chart_layout.py)
value_axis_crosses  # unused variable (python\gopptx\schemas_chart_layout.py)
present  # unused variable (python\gopptx\schemas_chart_layout.py)
tick_label_pos  # unused variable (python\gopptx\schemas_chart_layout.py)
major_gridline  # unused variable (python\gopptx\schemas_chart_layout.py)
crosses  # unused variable (python\gopptx\schemas_chart_layout.py)
chart_style  # unused variable (python\gopptx\schemas_chart_layout.py)
category_axis  # unused variable (python\gopptx\schemas_chart_layout.py)
value_axis  # unused variable (python\gopptx\schemas_chart_layout.py)
_.crosses  # unused property (python\gopptx\slide\chart\axis_series.py)
_.define_table_style  # unused method (python\gopptx\presentation\table_mixin.py)
_.list_table_styles  # unused method (python\gopptx\presentation\table_mixin.py)
scene3d  # unused variable (python\gopptx\schemas_chart_layout.py)
_.scene3d  # unused property (python\gopptx\slide\chart\scene3d_area.py)
_.chart_area  # unused property (python\gopptx\slide\chart\model.py)
_.update_shape_run_texts  # unused method (python\gopptx\slide\slide_text_mixin.py)

# Phase 1-3 additions: custom XML, notes, export, builder public API.
_.notes_slide_exists  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.add_custom_xml  # unused method (python\gopptx\presentation\custom_xml\custom_xml_mixin.py)
_.list_custom_xml  # unused method (python\gopptx\presentation\custom_xml\custom_xml_mixin.py)
_.remove_custom_xml  # unused method (python\gopptx\presentation\custom_xml\custom_xml_mixin.py)
_.save_as_pdf  # unused method (python\gopptx\presentation\export\export_mixin.py)
_.export_html  # unused method (python\gopptx\presentation\export\export_mixin.py)
font_paths  # unused variable (python\gopptx\presentation\export\export_mixin.py)
_.with_author  # unused method (python\gopptx\builder.py)
_.with_subject  # unused method (python\gopptx\builder.py)
_.with_keywords  # unused method (python\gopptx\builder.py)
_.with_description  # unused method (python\gopptx\builder.py)
_.with_theme  # unused method (python\gopptx\builder.py)
_.with_slide_size  # unused method (python\gopptx\builder.py)
_.with_modify_password  # unused method (python\gopptx\builder.py)
_.with_mark_as_final  # unused method (python\gopptx\builder.py)
_.update_chart_data_batch  # unused method (python\gopptx\presentation\charts\chart_mixin.py)

# Pre-existing public API on new modular files (axis_series, chart model, notes).
_.axis_kind  # unused property (python\gopptx\slide\chart\axis_series.py)
_.is_category_axis  # unused property (python\gopptx\slide\chart\axis_series.py)
_.is_value_axis  # unused property (python\gopptx\slide\chart\axis_series.py)
_.crosses_auto_zero  # unused property (python\gopptx\slide\chart\axis_series.py)
_.crosses_at_maximum  # unused property (python\gopptx\slide\chart\axis_series.py)
_.crosses_at_minimum  # unused property (python\gopptx\slide\chart\axis_series.py)
_.set_crosses_auto_zero  # unused method (python\gopptx\slide\chart\axis_series.py)
_.set_crosses_at_maximum  # unused method (python\gopptx\slide\chart\axis_series.py)
_.set_crosses_at_minimum  # unused method (python\gopptx\slide\chart\axis_series.py)
_.set_axis_crosses  # unused method (python\gopptx\slide\chart\model.py)
_.set_axis_gridlines  # unused method (python\gopptx\slide\chart\model.py)
_.set_tick_labels_visibility  # unused method (python\gopptx\slide\chart\model.py)
_.set_fill_solid  # unused method (python\gopptx\slide\notes\notes_shape.py)
_.set_line_color  # unused method (python\gopptx\slide\notes\notes_shape.py)
_.set_line_width  # unused method (python\gopptx\slide\notes\notes_shape.py)
_._set_shape_text  # unused method (python\gopptx\slide\notes\notes_slide.py)
_.shape_by_name  # unused method (python\gopptx\slide\notes\notes_slide.py)
_.set_shape_bounds  # unused method (python\gopptx\slide\notes\notes_slide.py)
_.set_shape_fill_background  # unused method (python\gopptx\slide\notes\notes_slide.py)
_.text_shapes  # unused property (python\gopptx\slide\notes\notes_slide.py)
_.placeholder_shapes  # unused property (python\gopptx\slide\notes\notes_slide.py)
_.set_shape_fill_gradient  # unused method (python\gopptx\slide\notes\notes_slide_style_mixin.py)
_.set_shape_fill_pattern  # unused method (python\gopptx\slide\notes\notes_slide_style_mixin.py)
_.set_shape_line_dash  # unused method (python\gopptx\slide\notes\notes_slide_style_mixin.py)
_._paragraph_texts  # unused method (python\gopptx\slide\notes\notes_text_model.py)
_._set_paragraph_texts  # unused method (python\gopptx\slide\notes\notes_text_model.py)
_.id  # unused property (python\gopptx\slide\shapes\shape_proxy.py)
_._shape_record_by_id  # unused method (python\gopptx\slide\slide.py)
category_axis_minor_gridlines  # unused variable (python\gopptx\schemas_chart_layout.py)
value_axis_minor_gridlines  # unused variable (python\gopptx\schemas_chart_layout.py)
minor_gridline  # unused variable (python\gopptx\schemas_chart_layout.py)

# Phase 5-8 additions: RunBuilder, Mermaid, Markdown, URL fetch.
_.set_runs  # unused method (python\gopptx\slide\text\text_model.py)
_.set_text_runs  # unused method (python\gopptx\slide\shapes\shape_proxy.py)
_.bold  # unused method (python\gopptx\text\run_builder.py)
_.italic  # unused method (python\gopptx\text\run_builder.py)
_.underline  # unused method (python\gopptx\text\run_builder.py)
_.strikethrough  # unused method (python\gopptx\text\run_builder.py)
_.subscript  # unused method (python\gopptx\text\run_builder.py)
_.superscript  # unused method (python\gopptx\text\run_builder.py)
_.color  # unused method (python\gopptx\text\run_builder.py)
_.highlight  # unused method (python\gopptx\text\run_builder.py)
_.font  # unused method (python\gopptx\text\run_builder.py)
_.size_pt  # unused method (python\gopptx\text\run_builder.py)
_.code  # unused method (python\gopptx\text\run_builder.py)
_.all_caps  # unused method (python\gopptx\text\run_builder.py)
_.small_caps  # unused method (python\gopptx\text\run_builder.py)
_.hyperlink  # unused method (python\gopptx\text\run_builder.py)
_.hover_action  # unused method (python\gopptx\text\run_builder.py)
_.build  # unused method (python\gopptx\text\run_builder.py)
_.to_payload  # unused method (python\gopptx\text\run_builder.py)
_.add_mermaid  # unused method (python\gopptx\slide\shapes\shape_mixin.py)
_.add_slide_from_markdown  # unused method (python\gopptx\presentation\slides\slides_mixin.py)
_.add_slide_from_url  # unused method (python\gopptx\presentation\slides\slides_mixin.py)

# ShapeBuilder public API
_.of  # unused method (python\gopptx\shapes\shape_builder.py)
_.rectangle  # unused method (python\gopptx\shapes\shape_builder.py)
_.rounded_rectangle  # unused method (python\gopptx\shapes\shape_builder.py)
_.ellipse  # unused method (python\gopptx\shapes\shape_builder.py)
_.triangle  # unused method (python\gopptx\shapes\shape_builder.py)
_.right_triangle  # unused method (python\gopptx\shapes\shape_builder.py)
_.diamond  # unused method (python\gopptx\shapes\shape_builder.py)
_.pentagon  # unused method (python\gopptx\shapes\shape_builder.py)
_.hexagon  # unused method (python\gopptx\shapes\shape_builder.py)
_.parallelogram  # unused method (python\gopptx\shapes\shape_builder.py)
_.cloud  # unused method (python\gopptx\shapes\shape_builder.py)
_.heart  # unused method (python\gopptx\shapes\shape_builder.py)
_.star5  # unused method (python\gopptx\shapes\shape_builder.py)
_.star6  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_text  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_fill  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_no_fill  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_line  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_no_line  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_shadow  # unused method (python\gopptx\shapes\shape_builder.py)
_.with_rotation  # unused method (python\gopptx\shapes\shape_builder.py)
_.flip_horizontal  # unused method (python\gopptx\shapes\shape_builder.py)
_.flip_vertical  # unused method (python\gopptx\shapes\shape_builder.py)
_.shape_type  # unused property (python\gopptx\shapes\shape_builder.py)
_.bounds  # unused property (python\gopptx\shapes\shape_builder.py)
_.to_kwargs  # unused method (python\gopptx\shapes\shape_builder.py)
_.add  # unused method (python\gopptx\slide\shapes\shape_proxy.py)

# Phase 9-11 additions: SmartArt, animations, transitions.
_.add_smartart  # unused method (python\gopptx\slide\shapes\smartart_anim_mixin.py)
_.add_animation  # unused method (python\gopptx\slide\shapes\smartart_anim_mixin.py)
_.set_transition  # unused method (python\gopptx\slide\shapes\smartart_anim_mixin.py)

# Phase 12+ additions: missing bridge ops.
_.list_notes_shapes  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.list_notes_placeholders  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.update_notes_master  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.list_slide_images  # unused method (python\gopptx\presentation\shapes\shape_media_mixin.py)
_.swap_image_by_index  # unused method (python\gopptx\presentation\shapes\shape_media_mixin.py)
_.swap_image_by_rel_id  # unused method (python\gopptx\presentation\shapes\shape_media_mixin.py)
_.move_shape_to_index  # unused method (python\gopptx\presentation\shapes\shapes_tables.py)
_.set_global_theme_preset  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.set_theme_font_scheme  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.set_theme_color_scheme  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.get_theme_inventory  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.get_layout_shapes  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.get_master_shapes  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.get_layout_placeholders  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.get_master_placeholders  # unused method (python\gopptx\presentation\slides\layout_theme_mixin.py)
_.validate  # unused method (python\gopptx\presentation\slides\properties_mixin.py)
_.repair  # unused method (python\gopptx\presentation\slides\properties_mixin.py)
_.duplicate_slide_after  # unused method (python\gopptx\presentation\slides\slides_mixin.py)
_.Target  # unused variable (python\gopptx\schemas_shape_types.py SlideImageRef)
_.merge_from_editor  # unused method (python\gopptx\presentation\slides\slides_mixin.py)

# Phase 13 additions: SmartArt update, slide background, header/footer, handout master, digital sig.
_.update_smartart  # unused method (python\gopptx\slide\shapes\smartart_anim_mixin.py)
_.set_background  # unused method (python\gopptx\slide\shapes\smartart_anim_mixin.py)
_.set_header_footer  # unused method (python\gopptx\slide\shapes\smartart_anim_mixin.py)
_.get_handout_master  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.update_handout_master  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.has_digital_signature  # unused method (python\gopptx\presentation\notes\notes_mixin.py)
_.clear_shapes  # unused method (python\gopptx\presentation\shapes\shapes_tables.py / python\gopptx\slide\shapes\shape_mixin.py)

# Notes text model formatting properties and alignment methods
_.font_size  # unused attribute (notes_text_model.py NotesParagraph/NotesRun)
_.bold  # unused attribute (notes_text_model.py NotesParagraph/NotesRun)
_.italic  # unused attribute (notes_text_model.py NotesParagraph/NotesRun)
_.color  # unused attribute (notes_text_model.py NotesParagraph/NotesRun)
_.alignment  # unused attribute (notes_text_model.py NotesParagraph)
_.align_left  # unused method (notes_text_model.py NotesParagraph)
_.align_center  # unused method (notes_text_model.py NotesParagraph)
_.align_right  # unused method (notes_text_model.py NotesParagraph)
_.align_justify  # unused method (notes_text_model.py NotesParagraph)

# 2026-03-23: Vulture false-positives after modular split/public API expansion.
STAR_7  # unused variable (python\gopptx\constants.py ShapeType)
STAR_8  # unused variable (python\gopptx\constants.py ShapeType)
STAR_10  # unused variable (python\gopptx\constants.py ShapeType)
STAR_12  # unused variable (python\gopptx\constants.py ShapeType)
STAR_16  # unused variable (python\gopptx\constants.py ShapeType)
STAR_24  # unused variable (python\gopptx\constants.py ShapeType)
STAR_32  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_PROCESS  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_DECISION  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_DATA  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_PREDEFINED_PROCESS  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_INTERNAL_STORAGE  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_DOCUMENT  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_MULTIDOCUMENT  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_TERMINATOR  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_PREPARATION  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_MANUAL_INPUT  # unused variable (python\gopptx\constants.py ShapeType)
FLOWCHART_MANUAL_OPERATION  # unused variable (python\gopptx\constants.py ShapeType)
CURVED_CONNECTOR_2  # unused variable (python\gopptx\constants.py enum members)
CURVED_CONNECTOR_3  # unused variable (python\gopptx\constants.py enum members)
CURVED_CONNECTOR_4  # unused variable (python\gopptx\constants.py enum members)
CURVED_CONNECTOR_5  # unused variable (python\gopptx\constants.py enum members)
BENT_CONNECTOR_2  # unused variable (python\gopptx\constants.py enum members)
BENT_CONNECTOR_3  # unused variable (python\gopptx\constants.py enum members)
BENT_CONNECTOR_4  # unused variable (python\gopptx\constants.py enum members)
BENT_CONNECTOR_5  # unused variable (python\gopptx\constants.py enum members)
STRAIGHT  # unused variable (python\gopptx\constants.py ConnectorType)
ELBOW  # unused variable (python\gopptx\constants.py ConnectorType)
CURVED  # unused variable (python\gopptx\constants.py ConnectorType)
_PresentationTemplateProtocol  # unused class (python\gopptx\presentation\base.py)
_GopptxLibProtocol  # unused class (python\gopptx\presentation\base.py)
ptr  # unused variable (python\gopptx\presentation\base.py)
_RawGopptxLibProtocol  # unused class (python\gopptx\presentation\base.py)
_.from_template  # unused method (python\gopptx\presentation\base.py)
_.render_template  # unused method (python\gopptx\presentation\base.py)
_PresentationSlidesProto  # unused class (python\gopptx\presentation\headers_footers_mixin.py)
_.get_header_footer  # unused method (python\gopptx\presentation\headers_footers_mixin.py)
_SlideExtrasProto  # unused class (python\gopptx\presentation\slides\slides_extras_mixin.py)
_.add_paragraph_slide  # unused method (python\gopptx\presentation\slides\slides_extras_mixin.py)
_TableBuilderProto  # unused class (python\gopptx\presentation\tables\table_builders.py)
_.add_table_from_dicts  # unused method (python\gopptx\presentation\tables\table_builders.py)
_.get_table_style_by_name  # unused method (python\gopptx\presentation\tables\table_style_mixin.py)
_.get_all_table_style_names  # unused method (python\gopptx\presentation\tables\table_style_mixin.py)
action  # unused variable (python\gopptx\schemas_shape_types.py)
target_slide  # unused variable (python\gopptx\schemas_shape_types.py)
jump  # unused variable (python\gopptx\schemas_shape_types.py)
macro  # unused variable (python\gopptx\schemas_shape_types.py)
history  # unused variable (python\gopptx\schemas_shape_types.py)
highlight_click  # unused variable (python\gopptx\schemas_shape_types.py)
end_sound  # unused variable (python\gopptx\schemas_shape_types.py)
flip_h  # unused variable (python\gopptx\schemas_shape_types.py)
flip_v  # unused variable (python\gopptx\schemas_shape_types.py)
_.set_data  # unused method (python\gopptx\slide\tables\table.py)
_TableProto  # unused class (python\gopptx\slide\tables\table_flags_mixin.py)
_TableFactoryProto  # unused class (python\gopptx\slide\tables\table_mixin.py)
SlideData  # unused class (python\gopptx\templates\_template_utils.py)
_.get_shape_center  # unused method (python\gopptx\presentation\shapes\shapes_tables.py)
_.shape_center  # unused method (python\gopptx\slide\shapes\shape_mixin.py)
_.find_by_slide_id  # unused method (python\gopptx\presentation\slides\collection.py) — tested via python_slide_objects_test.py
