// Command gen_shape_types generates pkg/pptx/shape_types.go from the
// canonical ShapeType* constants declared in pkg/pptx/shapes/shape_types_*.go.
// Constants already re-exported by pkg/pptx/shape_aliases.go (the core set)
// are skipped to avoid duplicate declarations.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	minCLIArgs        = 4
	shapeTypePrefix   = "ShapeType"
	sourceFilePattern = "shape_types_*.go"
)

type group struct {
	Name    string
	Heading string
	Idents  []string
}

// Trailing tags of the generated shape_types_<tag>.go files.
const (
	categoryBasic        = "basic"
	categoryArrows       = "arrows"
	categoryStars        = "stars"
	categoryCallouts     = "callouts"
	categoryFlowchart    = "flowchart"
	categoryAction       = "action"
	categoryMath         = "math"
	categoryRectVariants = "rect_variants"
)

// categoryHeading maps the trailing tag of shape_types_<tag>.go to a human-readable section heading.
//
//nolint:gochecknoglobals // build-time generator config; behaves as a const map
var categoryHeading = map[string]string{
	categoryBasic:        "Basic geometry (expanded).",
	categoryArrows:       "Arrows (expanded).",
	categoryStars:        "Stars, banners, scrolls.",
	categoryCallouts:     "Callouts.",
	categoryFlowchart:    "Flowcharts (expanded).",
	categoryAction:       "Action buttons.",
	categoryMath:         "Math and special shapes.",
	categoryRectVariants: "Rectangle variants.",
}

// orderedCategories controls emit order so the generated file matches conventional grouping.
//
//nolint:gochecknoglobals // build-time generator config; behaves as a const slice
var orderedCategories = []string{
	categoryBasic, categoryArrows, categoryStars, categoryCallouts,
	categoryFlowchart, categoryAction, categoryMath, categoryRectVariants,
}

func main() {
	if len(os.Args) < minCLIArgs {
		fmt.Fprintln(
			os.Stderr,
			"Usage: gen_shape_types <shapes_dir> <aliases_file> <output_file>",
		)
		os.Exit(1)
	}
	shapesDir := os.Args[1]
	aliasesFile := os.Args[2]
	outputFile := os.Args[3]

	skip, err := parseShapeIdents(aliasesFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse aliases: %v\n", err)
		os.Exit(1)
	}

	groups, err := loadGroups(shapesDir, skip)
	if err != nil {
		fmt.Fprintf(os.Stderr, "load groups: %v\n", err)
		os.Exit(1)
	}

	if err := writeOutput(outputFile, groups); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}

// parseShapeIdents returns the set of ShapeType* identifiers declared in path.
func parseShapeIdents(path string) (map[string]struct{}, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	idents := map[string]struct{}{}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range vs.Names {
				if strings.HasPrefix(name.Name, shapeTypePrefix) {
					idents[name.Name] = struct{}{}
				}
			}
		}
	}
	return idents, nil
}

func loadGroups(shapesDir string, skip map[string]struct{}) ([]group, error) {
	matches, err := filepath.Glob(filepath.Join(shapesDir, sourceFilePattern))
	if err != nil {
		return nil, err
	}
	byCategory := map[string][]string{}
	for _, m := range matches {
		category := categoryFromFilename(filepath.Base(m))
		if category == "" {
			continue
		}
		idents, err := parseShapeIdents(m)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", m, err)
		}
		for ident := range idents {
			if _, dup := skip[ident]; dup {
				continue
			}
			byCategory[category] = append(byCategory[category], ident)
		}
	}
	groups := make([]group, 0, len(orderedCategories))
	for _, cat := range orderedCategories {
		idents := byCategory[cat]
		if len(idents) == 0 {
			continue
		}
		sort.Strings(idents)
		groups = append(groups, group{
			Name:    cat,
			Heading: categoryHeading[cat],
			Idents:  idents,
		})
	}
	return groups, nil
}

func categoryFromFilename(name string) string {
	const prefix = "shape_types_"
	const suffix = ".go"
	if !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, suffix) {
		return ""
	}
	return strings.TrimSuffix(strings.TrimPrefix(name, prefix), suffix)
}

func writeOutput(path string, groups []group) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen_shape_types. DO NOT EDIT.\n\n")
	b.WriteString("package pptx\n\n")
	b.WriteString("import \"github.com/djinn-soul/gopptx/pkg/pptx/shapes\"\n\n")
	b.WriteString("// Shape type re-exports - expanded ECMA-376 presets.\n")
	b.WriteString("// Core shapes re-exported in shape_aliases.go; this file covers the extended catalog.\n\n")
	for i, g := range groups {
		fmt.Fprintf(&b, "// %s\n", g.Heading)
		b.WriteString("const (\n")
		maxLen := 0
		for _, id := range g.Idents {
			if len(id) > maxLen {
				maxLen = len(id)
			}
		}
		for _, id := range g.Idents {
			fmt.Fprintf(&b, "\t%-*s = shapes.%s\n", maxLen, id, id)
		}
		b.WriteString(")\n")
		if i < len(groups)-1 {
			b.WriteString("\n")
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}
