// Code generated by cmd/gen_shape_types. DO NOT EDIT.

package pptx

import "github.com/djinn-soul/gopptx/pkg/pptx/shapes"

// Shape type re-exports - expanded ECMA-376 presets.
// Core shapes re-exported in shape_aliases.go; this file covers the extended catalog.

// Basic geometry (expanded).
const (
	ShapeTypeArc                   = shapes.ShapeTypeArc
	ShapeTypeBevel                 = shapes.ShapeTypeBevel
	ShapeTypeBlockArc              = shapes.ShapeTypeBlockArc
	ShapeTypeCan                   = shapes.ShapeTypeCan
	ShapeTypeChevron               = shapes.ShapeTypeChevron
	ShapeTypeChord                 = shapes.ShapeTypeChord
	ShapeTypeCone                  = shapes.ShapeTypeCone
	ShapeTypeCorner                = shapes.ShapeTypeCorner
	ShapeTypeCube                  = shapes.ShapeTypeCube
	ShapeTypeCylinder              = shapes.ShapeTypeCylinder
	ShapeTypeDecagon               = shapes.ShapeTypeDecagon
	ShapeTypeDiagStripe            = shapes.ShapeTypeDiagStripe
	ShapeTypeDodecagon             = shapes.ShapeTypeDodecagon
	ShapeTypeDonut                 = shapes.ShapeTypeDonut
	ShapeTypeFoldedCorner          = shapes.ShapeTypeFoldedCorner
	ShapeTypeFrame                 = shapes.ShapeTypeFrame
	ShapeTypeFunnel                = shapes.ShapeTypeFunnel
	ShapeTypeHalfFrame             = shapes.ShapeTypeHalfFrame
	ShapeTypeHeptagon              = shapes.ShapeTypeHeptagon
	ShapeTypeHomePlate             = shapes.ShapeTypeHomePlate
	ShapeTypeIsoscelesTrapezoid    = shapes.ShapeTypeIsoscelesTrapezoid
	ShapeTypeLShape                = shapes.ShapeTypeLShape
	ShapeTypeLightningBolt         = shapes.ShapeTypeLightningBolt
	ShapeTypeMoon                  = shapes.ShapeTypeMoon
	ShapeTypeMusicNote             = shapes.ShapeTypeMusicNote
	ShapeTypeNoSmoking             = shapes.ShapeTypeNoSmoking
	ShapeTypeNonIsoscelesTrapezoid = shapes.ShapeTypeNonIsoscelesTrapezoid
	ShapeTypeOctagon               = shapes.ShapeTypeOctagon
	ShapeTypePictureFrame          = shapes.ShapeTypePictureFrame
	ShapeTypePie                   = shapes.ShapeTypePie
	ShapeTypePieWedge              = shapes.ShapeTypePieWedge
	ShapeTypePlaque                = shapes.ShapeTypePlaque
	ShapeTypePlus                  = shapes.ShapeTypePlus
	ShapeTypeSmileyFace            = shapes.ShapeTypeSmileyFace
	ShapeTypeSun                   = shapes.ShapeTypeSun
	ShapeTypeTeardrop              = shapes.ShapeTypeTeardrop
	ShapeTypeTrapezoid             = shapes.ShapeTypeTrapezoid
)

// Arrows (expanded).
const (
	ShapeTypeBentArrow             = shapes.ShapeTypeBentArrow
	ShapeTypeBentUpArrow           = shapes.ShapeTypeBentUpArrow
	ShapeTypeChevronArrow          = shapes.ShapeTypeChevronArrow
	ShapeTypeCircularArrow         = shapes.ShapeTypeCircularArrow
	ShapeTypeCurvedDownArrow       = shapes.ShapeTypeCurvedDownArrow
	ShapeTypeCurvedLeftArrow       = shapes.ShapeTypeCurvedLeftArrow
	ShapeTypeCurvedLeftRightArrow  = shapes.ShapeTypeCurvedLeftRightArrow
	ShapeTypeCurvedRightArrow      = shapes.ShapeTypeCurvedRightArrow
	ShapeTypeCurvedUpArrow         = shapes.ShapeTypeCurvedUpArrow
	ShapeTypeCurvedUpDownArrow     = shapes.ShapeTypeCurvedUpDownArrow
	ShapeTypeDownArrowCallout      = shapes.ShapeTypeDownArrowCallout
	ShapeTypeLeftArrowCallout      = shapes.ShapeTypeLeftArrowCallout
	ShapeTypeLeftRightArrow        = shapes.ShapeTypeLeftRightArrow
	ShapeTypeLeftRightArrowCallout = shapes.ShapeTypeLeftRightArrowCallout
	ShapeTypeLeftRightUpArrow      = shapes.ShapeTypeLeftRightUpArrow
	ShapeTypeLeftUpArrow           = shapes.ShapeTypeLeftUpArrow
	ShapeTypeNotchedRightArrow     = shapes.ShapeTypeNotchedRightArrow
	ShapeTypePentagonArrow         = shapes.ShapeTypePentagonArrow
	ShapeTypeQuadArrow             = shapes.ShapeTypeQuadArrow
	ShapeTypeQuadArrowCallout      = shapes.ShapeTypeQuadArrowCallout
	ShapeTypeRightArrowCallout     = shapes.ShapeTypeRightArrowCallout
	ShapeTypeStripedRightArrow     = shapes.ShapeTypeStripedRightArrow
	ShapeTypeSwooshArrow           = shapes.ShapeTypeSwooshArrow
	ShapeTypeUpArrowCallout        = shapes.ShapeTypeUpArrowCallout
	ShapeTypeUpDownArrow           = shapes.ShapeTypeUpDownArrow
	ShapeTypeUpDownArrowCallout    = shapes.ShapeTypeUpDownArrowCallout
	ShapeTypeUturnArrow            = shapes.ShapeTypeUturnArrow
)

// Stars, banners, scrolls.
const (
	ShapeTypeDoubleWave       = shapes.ShapeTypeDoubleWave
	ShapeTypeEllipseRibbon    = shapes.ShapeTypeEllipseRibbon
	ShapeTypeEllipseRibbon2   = shapes.ShapeTypeEllipseRibbon2
	ShapeTypeHorizontalScroll = shapes.ShapeTypeHorizontalScroll
	ShapeTypeIrregularSeal1   = shapes.ShapeTypeIrregularSeal1
	ShapeTypeIrregularSeal2   = shapes.ShapeTypeIrregularSeal2
	ShapeTypeRibbon           = shapes.ShapeTypeRibbon
	ShapeTypeRibbon2          = shapes.ShapeTypeRibbon2
	ShapeTypeSeal             = shapes.ShapeTypeSeal
	ShapeTypeSeal16           = shapes.ShapeTypeSeal16
	ShapeTypeSeal32           = shapes.ShapeTypeSeal32
	ShapeTypeSeal4            = shapes.ShapeTypeSeal4
	ShapeTypeSeal8            = shapes.ShapeTypeSeal8
	ShapeTypeStar10           = shapes.ShapeTypeStar10
	ShapeTypeStar12           = shapes.ShapeTypeStar12
	ShapeTypeStar16           = shapes.ShapeTypeStar16
	ShapeTypeStar24           = shapes.ShapeTypeStar24
	ShapeTypeStar32           = shapes.ShapeTypeStar32
	ShapeTypeStar4            = shapes.ShapeTypeStar4
	ShapeTypeStar6            = shapes.ShapeTypeStar6
	ShapeTypeStar7            = shapes.ShapeTypeStar7
	ShapeTypeStar8            = shapes.ShapeTypeStar8
	ShapeTypeVerticalScroll   = shapes.ShapeTypeVerticalScroll
	ShapeTypeWave             = shapes.ShapeTypeWave
)

// Callouts.
const (
	ShapeTypeAccentBorderCallout1 = shapes.ShapeTypeAccentBorderCallout1
	ShapeTypeAccentBorderCallout2 = shapes.ShapeTypeAccentBorderCallout2
	ShapeTypeAccentBorderCallout3 = shapes.ShapeTypeAccentBorderCallout3
	ShapeTypeAccentCallout1       = shapes.ShapeTypeAccentCallout1
	ShapeTypeAccentCallout2       = shapes.ShapeTypeAccentCallout2
	ShapeTypeAccentCallout3       = shapes.ShapeTypeAccentCallout3
	ShapeTypeBorderCallout1       = shapes.ShapeTypeBorderCallout1
	ShapeTypeBorderCallout2       = shapes.ShapeTypeBorderCallout2
	ShapeTypeBorderCallout3       = shapes.ShapeTypeBorderCallout3
	ShapeTypeCallout1             = shapes.ShapeTypeCallout1
	ShapeTypeCallout2             = shapes.ShapeTypeCallout2
	ShapeTypeCallout3             = shapes.ShapeTypeCallout3
	ShapeTypeCloudCallout         = shapes.ShapeTypeCloudCallout
	ShapeTypeWedgeEllipseCallout  = shapes.ShapeTypeWedgeEllipseCallout
	ShapeTypeWedgeRRectCallout    = shapes.ShapeTypeWedgeRRectCallout
	ShapeTypeWedgeRectCallout     = shapes.ShapeTypeWedgeRectCallout
)

// Flowcharts (expanded).
const (
	ShapeTypeFlowChartAlternateProcess        = shapes.ShapeTypeFlowChartAlternateProcess
	ShapeTypeFlowChartCard                    = shapes.ShapeTypeFlowChartCard
	ShapeTypeFlowChartCollate                 = shapes.ShapeTypeFlowChartCollate
	ShapeTypeFlowChartConnector               = shapes.ShapeTypeFlowChartConnector
	ShapeTypeFlowChartDelay                   = shapes.ShapeTypeFlowChartDelay
	ShapeTypeFlowChartDirectAccessStorage     = shapes.ShapeTypeFlowChartDirectAccessStorage
	ShapeTypeFlowChartDisplay                 = shapes.ShapeTypeFlowChartDisplay
	ShapeTypeFlowChartExtract                 = shapes.ShapeTypeFlowChartExtract
	ShapeTypeFlowChartInputOutput             = shapes.ShapeTypeFlowChartInputOutput
	ShapeTypeFlowChartInternalStorage         = shapes.ShapeTypeFlowChartInternalStorage
	ShapeTypeFlowChartMagneticDisk            = shapes.ShapeTypeFlowChartMagneticDisk
	ShapeTypeFlowChartMagneticDrum            = shapes.ShapeTypeFlowChartMagneticDrum
	ShapeTypeFlowChartMagneticTape            = shapes.ShapeTypeFlowChartMagneticTape
	ShapeTypeFlowChartManualInput             = shapes.ShapeTypeFlowChartManualInput
	ShapeTypeFlowChartManualOperation         = shapes.ShapeTypeFlowChartManualOperation
	ShapeTypeFlowChartMerge                   = shapes.ShapeTypeFlowChartMerge
	ShapeTypeFlowChartMultidocument           = shapes.ShapeTypeFlowChartMultidocument
	ShapeTypeFlowChartOffpageConnector        = shapes.ShapeTypeFlowChartOffpageConnector
	ShapeTypeFlowChartOnlineStorage           = shapes.ShapeTypeFlowChartOnlineStorage
	ShapeTypeFlowChartOr                      = shapes.ShapeTypeFlowChartOr
	ShapeTypeFlowChartPredefinedProcess       = shapes.ShapeTypeFlowChartPredefinedProcess
	ShapeTypeFlowChartPreparation             = shapes.ShapeTypeFlowChartPreparation
	ShapeTypeFlowChartPunchedCard             = shapes.ShapeTypeFlowChartPunchedCard
	ShapeTypeFlowChartPunchedTape             = shapes.ShapeTypeFlowChartPunchedTape
	ShapeTypeFlowChartSequentialAccessStorage = shapes.ShapeTypeFlowChartSequentialAccessStorage
	ShapeTypeFlowChartSort                    = shapes.ShapeTypeFlowChartSort
	ShapeTypeFlowChartStoredData              = shapes.ShapeTypeFlowChartStoredData
	ShapeTypeFlowChartSummingJunction         = shapes.ShapeTypeFlowChartSummingJunction
)

// Action buttons.
const (
	ShapeTypeActionButtonBackPrevious = shapes.ShapeTypeActionButtonBackPrevious
	ShapeTypeActionButtonBeginning    = shapes.ShapeTypeActionButtonBeginning
	ShapeTypeActionButtonBlank        = shapes.ShapeTypeActionButtonBlank
	ShapeTypeActionButtonDocument     = shapes.ShapeTypeActionButtonDocument
	ShapeTypeActionButtonEnd          = shapes.ShapeTypeActionButtonEnd
	ShapeTypeActionButtonForwardNext  = shapes.ShapeTypeActionButtonForwardNext
	ShapeTypeActionButtonHelp         = shapes.ShapeTypeActionButtonHelp
	ShapeTypeActionButtonHome         = shapes.ShapeTypeActionButtonHome
	ShapeTypeActionButtonInformation  = shapes.ShapeTypeActionButtonInformation
	ShapeTypeActionButtonMovie        = shapes.ShapeTypeActionButtonMovie
	ShapeTypeActionButtonReturn       = shapes.ShapeTypeActionButtonReturn
	ShapeTypeActionButtonSound        = shapes.ShapeTypeActionButtonSound
)

// Math and special shapes.
const (
	ShapeTypeBracePair     = shapes.ShapeTypeBracePair
	ShapeTypeBracketPair   = shapes.ShapeTypeBracketPair
	ShapeTypeChartPlus     = shapes.ShapeTypeChartPlus
	ShapeTypeChartStar     = shapes.ShapeTypeChartStar
	ShapeTypeChartX        = shapes.ShapeTypeChartX
	ShapeTypeDoubleBrace   = shapes.ShapeTypeDoubleBrace
	ShapeTypeDoubleBracket = shapes.ShapeTypeDoubleBracket
	ShapeTypeGear6         = shapes.ShapeTypeGear6
	ShapeTypeGear9         = shapes.ShapeTypeGear9
	ShapeTypeLeftBrace     = shapes.ShapeTypeLeftBrace
	ShapeTypeLeftBracket   = shapes.ShapeTypeLeftBracket
	ShapeTypeLine          = shapes.ShapeTypeLine
	ShapeTypeLineInv       = shapes.ShapeTypeLineInv
	ShapeTypeMathDivide    = shapes.ShapeTypeMathDivide
	ShapeTypeMathEqual     = shapes.ShapeTypeMathEqual
	ShapeTypeMathMinus     = shapes.ShapeTypeMathMinus
	ShapeTypeMathMultiply  = shapes.ShapeTypeMathMultiply
	ShapeTypeMathNotEqual  = shapes.ShapeTypeMathNotEqual
	ShapeTypeMathPlus      = shapes.ShapeTypeMathPlus
	ShapeTypeRightBrace    = shapes.ShapeTypeRightBrace
	ShapeTypeRightBracket  = shapes.ShapeTypeRightBracket
)

// Rectangle variants.
const (
	ShapeTypeCornerTabs     = shapes.ShapeTypeCornerTabs
	ShapeTypePlaqueTabs     = shapes.ShapeTypePlaqueTabs
	ShapeTypeRound1Rect     = shapes.ShapeTypeRound1Rect
	ShapeTypeRound2DiagRect = shapes.ShapeTypeRound2DiagRect
	ShapeTypeRound2SameRect = shapes.ShapeTypeRound2SameRect
	ShapeTypeSnip1Rect      = shapes.ShapeTypeSnip1Rect
	ShapeTypeSnip2DiagRect  = shapes.ShapeTypeSnip2DiagRect
	ShapeTypeSnip2SameRect  = shapes.ShapeTypeSnip2SameRect
	ShapeTypeSnipRoundRect  = shapes.ShapeTypeSnipRoundRect
	ShapeTypeSquareTabs     = shapes.ShapeTypeSquareTabs
)
