package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// formatted runs the emitted source through gofmt, so the committed files are
// byte-identical to what the generator produces and the staleness check in
// main_test.go can compare them exactly.
func formatted(src string) (string, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("gofmt generated source: %w", err)
	}
	return string(out), nil
}

// maxMethodsPerFile keeps each generated file comfortably under the
// repository's 300-line per-file ceiling (see scripts/ci/architectural_guardrails.json).
const maxMethodsPerFile = 40

// chunkMethods splits methods into groups small enough to emit one per file.
func chunkMethods(methods []method) [][]method {
	var chunks [][]method
	for start := 0; start < len(methods); start += maxMethodsPerFile {
		end := min(start+maxMethodsPerFile, len(methods))
		chunks = append(chunks, methods[start:end])
	}
	return chunks
}

// importsFor returns only the imports the given chunk's signatures need.
func importsFor(chunk []method, available map[string]string) []string {
	needed := map[string]bool{}
	for _, m := range chunk {
		for _, qualifier := range m.Quals {
			needed[qualifier] = true
		}
	}

	paths := make([]string, 0, len(needed))
	for qualifier := range needed {
		if path, ok := available[qualifier]; ok {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	return paths
}

func renderCore() (string, error) {
	return formatted(generatedHeader + builderCore)
}

func renderChunk(chunk []method, imports []string) (string, error) {
	var out strings.Builder
	out.WriteString(generatedHeader)

	if len(imports) > 0 {
		out.WriteString("import (\n")
		for _, path := range imports {
			fmt.Fprintf(&out, "\t%q\n", path)
		}
		out.WriteString(")\n\n")
	}

	for _, m := range chunk {
		if m.Doc != "" {
			fmt.Fprintf(&out, "// %s %s\n", m.Name, m.Doc)
		} else {
			fmt.Fprintf(&out, "// %s calls SlideContent.%s on the wrapped slide.\n", m.Name, m.Name)
		}
		fmt.Fprintf(&out, "func (b *SlideBuilder) %s(%s) *SlideBuilder {\n", m.Name, m.Params)
		fmt.Fprintf(&out, "\tb.content = b.content.%s(%s)\n", m.Name, m.Args)
		out.WriteString("\treturn b\n}\n\n")
	}
	return formatted(out.String())
}

const generatedHeader = `// Code generated by cmd/gen_slide_builder. DO NOT EDIT.

package elements

`

const builderCore = `// SlideBuilder builds a SlideContent through pointer-receiver methods.
//
// SlideContent's own chainable methods take a value receiver, so dropping the
// returned value silently discards the change and the compiler says nothing:
//
//	s := NewSlide("t")
//	s.AddBullet("lost") // no effect
//
// SlideBuilder mutates in place, so the same mistake is impossible:
//
//	b := NewSlideBuilder("t")
//	b.AddBullet("kept") // applied
//	slide := b.Build()
//
// Every method returns the builder, so calls still chain.
type SlideBuilder struct {
	content SlideContent
}

// NewSlideBuilder starts a builder for a slide with the given title.
func NewSlideBuilder(title string) *SlideBuilder {
	return &SlideBuilder{content: NewSlide(title)}
}

// BuildFrom starts a builder from an existing SlideContent, so code already
// holding one can switch to the pointer-receiver style.
func BuildFrom(content SlideContent) *SlideBuilder {
	return &SlideBuilder{content: content}
}

// Build returns the SlideContent assembled so far.
func (b *SlideBuilder) Build() SlideContent {
	return b.content
}
`
