from .constants import ShapeType
from .schemas import TextRun

class ShapeBuilder:
    def __init__(
        self, shape_type: ShapeType, x: float, y: float, w: float, h: float
    ) -> None: ...
    @classmethod
    def of(
        cls, shape_type: ShapeType, x: float, y: float, w: float, h: float
    ) -> ShapeBuilder: ...
    @classmethod
    def rectangle(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def rounded_rectangle(
        cls, x: float, y: float, w: float, h: float
    ) -> ShapeBuilder: ...
    @classmethod
    def ellipse(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def triangle(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def right_triangle(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def diamond(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def pentagon(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def hexagon(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def parallelogram(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def cloud(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def heart(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def star5(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def star6(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    def with_text(self, text: str) -> ShapeBuilder: ...
    def with_fill(self, color: str) -> ShapeBuilder: ...
    def with_no_fill(self) -> ShapeBuilder: ...
    def with_line(
        self,
        color: str,
        *,
        width_emu: int | None = ...,
        dash_style: str | None = ...,
        start_arrow: str | None = ...,
        start_arrow_width: str | None = ...,
        start_arrow_length: str | None = ...,
        end_arrow: str | None = ...,
        end_arrow_width: str | None = ...,
        end_arrow_length: str | None = ...,
    ) -> ShapeBuilder: ...
    def with_no_line(self) -> ShapeBuilder: ...
    def with_shadow(
        self,
        color: str = ...,
        *,
        blur_emu: int | None = ...,
        distance_emu: int | None = ...,
        angle_deg: float = ...,
    ) -> ShapeBuilder: ...
    def with_rotation(self, degrees: float) -> ShapeBuilder: ...
    def flip_horizontal(self) -> ShapeBuilder: ...
    def flip_vertical(self) -> ShapeBuilder: ...
    @property
    def shape_type(self) -> str: ...
    @property
    def bounds(self) -> tuple[float, float, float, float]: ...
    def to_kwargs(self) -> dict[str, object]: ...

class RunBuilder:
    def __init__(self, text: str = "") -> None: ...
    def text(self, value: str) -> RunBuilder: ...
    def bold(self, *, value: bool = True) -> RunBuilder: ...
    def italic(self, *, value: bool = True) -> RunBuilder: ...
    def underline(self, style: str = "sng") -> RunBuilder: ...
    def strikethrough(self, style: str = "sng") -> RunBuilder: ...
    def subscript(self, *, value: bool = True) -> RunBuilder: ...
    def superscript(self, *, value: bool = True) -> RunBuilder: ...
    def color(self, hex_color: str) -> RunBuilder: ...
    def highlight(self, hex_color: str) -> RunBuilder: ...
    def font(self, name: str) -> RunBuilder: ...
    def size_pt(self, points: int) -> RunBuilder: ...
    def code(self, *, value: bool = True) -> RunBuilder: ...
    def all_caps(self, *, value: bool = True) -> RunBuilder: ...
    def small_caps(self, *, value: bool = True) -> RunBuilder: ...
    def hyperlink(self, address: str, *, tooltip: str = "") -> RunBuilder: ...
    def hover_action(self, address: str) -> RunBuilder: ...
    def build(self) -> TextRun: ...
    def to_payload(self) -> dict[str, object]: ...

class ShapeTextFrame:
    def set_runs(self, builders: list[RunBuilder]) -> None: ...

class ShapeProxy:
    def set_text_runs(self, builders: list[RunBuilder]) -> None: ...
