from collections.abc import Iterator, Sequence

from .schemas import (
    ChartDataLabelPointSpec,
    ChartDataPointSpec,
    ChartDataUpdate,
    ChartErrorBarSpec,
    ChartTrendlineSpec,
)

class FreeformBuilder:
    def move_to(self, x: float, y: float) -> FreeformBuilder: ...
    def add_line_to(self, x: float, y: float) -> FreeformBuilder: ...
    def add_line_segments(
        self, points: list[tuple[float, float]]
    ) -> FreeformBuilder: ...
    def convert_to_shape(self, *, close: bool = False, **kwargs: object) -> int: ...

class CategorySeries:
    name: str
    values: list[float]

class CategoryChartData:
    categories: list[str]
    series: list[CategorySeries]
    def add_category(self, value: str) -> None: ...
    def add_series(self, name: str, values: list[float]) -> None: ...
    def to_add_chart_args(
        self,
    ) -> tuple[list[str], list[float] | list[dict[str, object]]]: ...
    def to_update_payload(self) -> dict[str, object]: ...

class XySeries:
    name: str
    x_values: list[float]
    y_values: list[float]
    sizes: list[float] | None

class XyChartData:
    series: list[XySeries]
    def add_series(
        self,
        name: str,
        x_values: list[float],
        y_values: list[float],
        sizes: list[float] | None = None,
    ) -> None: ...
    def to_update_payload(self) -> dict[str, object]: ...
    def to_add_chart_args(
        self,
    ) -> tuple[list[str], list[float] | list[dict[str, object]]]: ...

class DataLabels:
    @property
    def show_value(self) -> bool: ...
    @show_value.setter
    def show_value(self, value: bool) -> None: ...
    @property
    def show_category_name(self) -> bool: ...
    @show_category_name.setter
    def show_category_name(self, value: bool) -> None: ...
    @property
    def position(self) -> str | None: ...
    @position.setter
    def position(self, value: str) -> None: ...
    @property
    def show_series_name(self) -> bool: ...
    @show_series_name.setter
    def show_series_name(self, value: bool) -> None: ...
    @property
    def number_format(self) -> str | None: ...
    @number_format.setter
    def number_format(self, value: str) -> None: ...
    @property
    def word_wrap(self) -> bool | None: ...
    @word_wrap.setter
    def word_wrap(self, value: bool) -> None: ...

class ChartPlot:
    @property
    def data_labels_visible(self) -> bool: ...
    @data_labels_visible.setter
    def data_labels_visible(self, value: bool) -> None: ...
    @property
    def data_labels(self) -> DataLabels: ...
    def set_bar_options(
        self, *, grouping: str, gap_width: int, overlap: int
    ) -> None: ...

class ChartPlots:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ChartPlot: ...
    def __iter__(self) -> Iterator[ChartPlot]: ...

class ChartTitle:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...

class ChartLegend:
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def position(self) -> str: ...
    @position.setter
    def position(self, value: str) -> None: ...
    @property
    def include_in_layout(self) -> bool: ...
    @include_in_layout.setter
    def include_in_layout(self, value: bool) -> None: ...

class ChartAxis:
    @property
    def present(self) -> bool: ...
    @property
    def tick_label_position(self) -> str | None: ...
    @tick_label_position.setter
    def tick_label_position(self, value: str) -> None: ...
    @property
    def major_gridlines_visible(self) -> bool: ...
    @major_gridlines_visible.setter
    def major_gridlines_visible(self, value: bool) -> None: ...
    @property
    def minor_gridlines_visible(self) -> bool: ...
    @minor_gridlines_visible.setter
    def minor_gridlines_visible(self, value: bool) -> None: ...
    @property
    def crosses(self) -> str | None: ...
    @crosses.setter
    def crosses(self, value: str) -> None: ...
    @property
    def title(self) -> str | None: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def minimum_scale(self) -> float | None: ...
    @minimum_scale.setter
    def minimum_scale(self, value: float) -> None: ...
    @property
    def maximum_scale(self) -> float | None: ...
    @maximum_scale.setter
    def maximum_scale(self, value: float) -> None: ...
    @property
    def major_unit(self) -> float | None: ...
    @major_unit.setter
    def major_unit(self, value: float) -> None: ...
    @property
    def minor_unit(self) -> float | None: ...
    @minor_unit.setter
    def minor_unit(self, value: float) -> None: ...
    @property
    def tick_mark_skip(self) -> int | None: ...
    @tick_mark_skip.setter
    def tick_mark_skip(self, value: int) -> None: ...
    @property
    def label_alignment(self) -> str | None: ...
    @label_alignment.setter
    def label_alignment(self, value: str) -> None: ...
    @property
    def tick_label_number_format(self) -> str | None: ...
    @tick_label_number_format.setter
    def tick_label_number_format(self, value: str) -> None: ...
    @property
    def tick_label_number_format_is_linked(self) -> bool | None: ...
    @tick_label_number_format_is_linked.setter
    def tick_label_number_format_is_linked(self, value: bool) -> None: ...

class ChartScene3D:
    @property
    def camera_preset(self) -> str | None: ...
    @camera_preset.setter
    def camera_preset(self, value: str) -> None: ...
    @property
    def camera_field_of_view(self) -> int | None: ...
    @camera_field_of_view.setter
    def camera_field_of_view(self, value: int) -> None: ...
    @property
    def light_rig(self) -> str | None: ...
    @light_rig.setter
    def light_rig(self, value: str) -> None: ...
    @property
    def light_direction(self) -> str | None: ...
    @light_direction.setter
    def light_direction(self, value: str) -> None: ...
    @property
    def light_rig_revolution(self) -> bool | None: ...
    @light_rig_revolution.setter
    def light_rig_revolution(self, value: bool) -> None: ...
    def update(
        self,
        *,
        camera_preset: str,
        light_rig: str,
        light_direction: str,
        camera_field_of_view: int | None = None,
        light_rig_revolution: bool | None = None,
    ) -> None: ...

class ChartArea:
    @property
    def scene3d(self) -> ChartScene3D: ...

class ChartSeries:
    @property
    def name(self) -> str | None: ...
    @property
    def values(self) -> list[float]: ...

class ChartSeriesCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ChartSeries: ...
    def __iter__(self) -> Iterator[ChartSeries]: ...

class Chart:
    @property
    def index(self) -> int: ...
    @property
    def rel_id(self) -> str: ...
    @property
    def chart_part(self) -> str: ...
    @property
    def chart_title(self) -> ChartTitle: ...
    @property
    def title_visible(self) -> bool: ...
    @title_visible.setter
    def title_visible(self, value: bool) -> None: ...
    @property
    def legend(self) -> ChartLegend: ...
    @property
    def plots(self) -> ChartPlots: ...
    @property
    def chart_area(self) -> ChartArea: ...
    @property
    def category_axis(self) -> ChartAxis: ...
    @property
    def value_axis(self) -> ChartAxis: ...
    @property
    def chart_style(self) -> int | None: ...
    @property
    def series(self) -> ChartSeriesCollection: ...
    @property
    def trendlines(self) -> TrendlineCollection: ...
    def add_trendline(
        self,
        trendline_type: str,
        *,
        series_index: int = 0,
        **options: object,
    ) -> None: ...
    def set_trendlines(
        self,
        trendlines: Sequence[ChartTrendlineSpec],
        *,
        series_index: int = 0,
    ) -> None: ...
    def clear_trendlines(self, *, series_index: int = 0) -> None: ...
    @property
    def error_bars(self) -> ErrorBarCollection: ...
    def add_error_bars(
        self,
        bar_type: str,
        value_type: str,
        *,
        series_index: int = 0,
        **options: object,
    ) -> None: ...
    def set_error_bars(
        self,
        error_bars: Sequence[ChartErrorBarSpec],
        *,
        series_index: int = 0,
    ) -> None: ...
    def clear_error_bars(self, *, series_index: int = 0) -> None: ...
    @property
    def data_points(self) -> DataPointCollection: ...
    def format_data_point(
        self,
        point_index: int,
        *,
        series_index: int = 0,
        **options: object,
    ) -> None: ...
    def format_data_points(
        self,
        points: Sequence[ChartDataPointSpec],
        *,
        series_index: int = 0,
    ) -> None: ...
    def clear_data_point_formatting(self, *, series_index: int = 0) -> None: ...
    @property
    def data_label_points(self) -> DataLabelPointCollection: ...
    def format_data_label(
        self,
        point_index: int,
        *,
        series_index: int = 0,
        **options: object,
    ) -> None: ...
    def format_data_labels(
        self,
        labels: Sequence[ChartDataLabelPointSpec],
        *,
        series_index: int = 0,
    ) -> None: ...
    def set_data_label_number_format(
        self,
        point_index: int,
        number_format: str,
        *,
        series_index: int = 0,
    ) -> None: ...
    @property
    def data_table(self) -> ChartDataTable: ...
    def set_invert_if_negative(
        self,
        *,
        enabled: bool = True,
        series_index: int = 0,
        negative_fill_color: str | None = None,
    ) -> None: ...
    def replace_data(
        self,
        data: CategoryChartData | XyChartData | ChartDataUpdate,
    ) -> None: ...

class Trendline:
    @property
    def series_index(self) -> int: ...
    @property
    def trendline_type(self) -> str | None: ...
    @property
    def order(self) -> int | None: ...
    @property
    def period(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def display_r_squared(self) -> bool | None: ...
    @property
    def display_equation(self) -> bool | None: ...
    def to_payload(self) -> dict[str, object]: ...

class TrendlineCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Trendline: ...
    def __iter__(self) -> Iterator[Trendline]: ...
    def for_series(self, series_index: int) -> list[Trendline]: ...

class ErrorBars:
    @property
    def series_index(self) -> int: ...
    @property
    def bar_type(self) -> str | None: ...
    @property
    def value_type(self) -> str | None: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def value(self) -> float | None: ...
    @property
    def plus_reference(self) -> str | None: ...
    @property
    def minus_reference(self) -> str | None: ...
    @property
    def no_end_cap(self) -> bool | None: ...
    def to_payload(self) -> dict[str, object]: ...

class ErrorBarCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ErrorBars: ...
    def __iter__(self) -> Iterator[ErrorBars]: ...
    def for_series(self, series_index: int) -> list[ErrorBars]: ...

class ChartDataTable:
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def show_horizontal_border(self) -> bool | None: ...
    @show_horizontal_border.setter
    def show_horizontal_border(self, value: bool) -> None: ...
    @property
    def show_vertical_border(self) -> bool | None: ...
    @show_vertical_border.setter
    def show_vertical_border(self, value: bool) -> None: ...
    @property
    def show_outline(self) -> bool | None: ...
    @show_outline.setter
    def show_outline(self, value: bool) -> None: ...
    @property
    def show_legend_keys(self) -> bool | None: ...
    @show_legend_keys.setter
    def show_legend_keys(self, value: bool) -> None: ...
    @property
    def font_size_pt(self) -> int | None: ...
    @font_size_pt.setter
    def font_size_pt(self, value: int) -> None: ...
    def show(
        self,
        *,
        horizontal_border: bool | None = None,
        vertical_border: bool | None = None,
        outline: bool | None = None,
        legend_keys: bool | None = None,
        font_size_pt: int | None = None,
    ) -> None: ...
    def hide(self) -> None: ...

class DataPoint:
    @property
    def series_index(self) -> int: ...
    @property
    def point_index(self) -> int: ...
    @property
    def fill_color(self) -> str | None: ...
    @property
    def line_color(self) -> str | None: ...
    @property
    def line_width_emu(self) -> int | None: ...
    @property
    def invert_if_negative(self) -> bool | None: ...
    @property
    def explosion(self) -> int | None: ...
    @property
    def marker_fill_color(self) -> str | None: ...
    @property
    def marker_line_color(self) -> str | None: ...
    @property
    def marker_symbol(self) -> str | None: ...
    @property
    def marker_size(self) -> int | None: ...
    def to_payload(self) -> dict[str, object]: ...

class DataPointCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> DataPoint: ...
    def __iter__(self) -> Iterator[DataPoint]: ...
    def for_series(self, series_index: int) -> list[DataPoint]: ...

class DataLabelPoint:
    @property
    def series_index(self) -> int: ...
    @property
    def point_index(self) -> int: ...
    @property
    def number_format(self) -> str | None: ...
    @property
    def format_linked(self) -> bool | None: ...
    @property
    def font_color(self) -> str | None: ...
    @property
    def font_size_pt(self) -> int | None: ...
    @property
    def font_bold(self) -> bool | None: ...
    @property
    def show_value(self) -> bool | None: ...
    @property
    def show_category(self) -> bool | None: ...
    @property
    def show_series_name(self) -> bool | None: ...
    @property
    def show_percent(self) -> bool | None: ...
    @property
    def deleted(self) -> bool: ...
    def to_payload(self) -> dict[str, object]: ...

class DataLabelPointCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> DataLabelPoint: ...
    def __iter__(self) -> Iterator[DataLabelPoint]: ...
    def for_series(self, series_index: int) -> list[DataLabelPoint]: ...
    def for_point(
        self, point_index: int, *, series_index: int = 0
    ) -> DataLabelPoint | None: ...

class ChartCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Chart: ...
    def __iter__(self) -> Iterator[Chart]: ...
