from collections.abc import Iterator

from .schemas import ChartDataUpdate

class FreeformBuilder:
    def move_to(self, x: float, y: float) -> FreeformBuilder: ...
    def add_line_to(self, x: float, y: float) -> FreeformBuilder: ...
    def add_line_segments(
        self, points: list[tuple[float, float]]
    ) -> FreeformBuilder: ...
    def convert_to_shape(self, *, close: bool = False, **kwargs: object) -> int: ...

class CategorySeries:
    name: str
    values: list[float]

class CategoryChartData:
    categories: list[str]
    series: list[CategorySeries]
    def add_category(self, value: str) -> None: ...
    def add_series(self, name: str, values: list[float]) -> None: ...
    def to_add_chart_args(
        self,
    ) -> tuple[list[str], list[float] | list[dict[str, object]]]: ...
    def to_update_payload(self) -> dict[str, object]: ...

class XySeries:
    name: str
    x_values: list[float]
    y_values: list[float]
    sizes: list[float] | None

class XyChartData:
    series: list[XySeries]
    def add_series(
        self,
        name: str,
        x_values: list[float],
        y_values: list[float],
        sizes: list[float] | None = None,
    ) -> None: ...
    def to_update_payload(self) -> dict[str, object]: ...
    def to_add_chart_args(
        self,
    ) -> tuple[list[str], list[float] | list[dict[str, object]]]: ...

class DataLabels:
    @property
    def show_value(self) -> bool: ...
    @show_value.setter
    def show_value(self, value: bool) -> None: ...
    @property
    def show_category_name(self) -> bool: ...
    @show_category_name.setter
    def show_category_name(self, value: bool) -> None: ...

class ChartPlot:
    @property
    def data_labels_visible(self) -> bool: ...
    @data_labels_visible.setter
    def data_labels_visible(self, value: bool) -> None: ...
    @property
    def data_labels(self) -> DataLabels: ...

class ChartPlots:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ChartPlot: ...
    def __iter__(self) -> Iterator[ChartPlot]: ...

class ChartTitle:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...

class ChartLegend:
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def position(self) -> str: ...
    @position.setter
    def position(self, value: str) -> None: ...
    @property
    def include_in_layout(self) -> bool: ...
    @include_in_layout.setter
    def include_in_layout(self, value: bool) -> None: ...

class ChartAxis:
    @property
    def present(self) -> bool: ...
    @property
    def tick_label_position(self) -> str | None: ...
    @tick_label_position.setter
    def tick_label_position(self, value: str) -> None: ...
    @property
    def major_gridlines_visible(self) -> bool: ...
    @major_gridlines_visible.setter
    def major_gridlines_visible(self, value: bool) -> None: ...
    @property
    def crosses(self) -> str | None: ...
    @crosses.setter
    def crosses(self, value: str) -> None: ...

class ChartScene3D:
    @property
    def camera_preset(self) -> str | None: ...
    @camera_preset.setter
    def camera_preset(self, value: str) -> None: ...
    @property
    def camera_field_of_view(self) -> int | None: ...
    @camera_field_of_view.setter
    def camera_field_of_view(self, value: int) -> None: ...
    @property
    def light_rig(self) -> str | None: ...
    @light_rig.setter
    def light_rig(self, value: str) -> None: ...
    @property
    def light_direction(self) -> str | None: ...
    @light_direction.setter
    def light_direction(self, value: str) -> None: ...
    @property
    def light_rig_revolution(self) -> bool | None: ...
    @light_rig_revolution.setter
    def light_rig_revolution(self, value: bool) -> None: ...
    def update(
        self,
        *,
        camera_preset: str,
        light_rig: str,
        light_direction: str,
        camera_field_of_view: int | None = None,
        light_rig_revolution: bool | None = None,
    ) -> None: ...

class ChartArea:
    @property
    def scene3d(self) -> ChartScene3D: ...

class ChartSeries:
    @property
    def name(self) -> str | None: ...
    @property
    def values(self) -> list[float]: ...

class ChartSeriesCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ChartSeries: ...
    def __iter__(self) -> Iterator[ChartSeries]: ...

class Chart:
    @property
    def index(self) -> int: ...
    @property
    def rel_id(self) -> str: ...
    @property
    def chart_part(self) -> str: ...
    @property
    def chart_title(self) -> ChartTitle: ...
    @property
    def title_visible(self) -> bool: ...
    @title_visible.setter
    def title_visible(self, value: bool) -> None: ...
    @property
    def legend(self) -> ChartLegend: ...
    @property
    def plots(self) -> ChartPlots: ...
    @property
    def chart_area(self) -> ChartArea: ...
    @property
    def category_axis(self) -> ChartAxis: ...
    @property
    def value_axis(self) -> ChartAxis: ...
    @property
    def chart_style(self) -> int | None: ...
    @property
    def series(self) -> ChartSeriesCollection: ...
    def replace_data(
        self,
        data: CategoryChartData | XyChartData | ChartDataUpdate,
    ) -> None: ...

class ChartCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Chart: ...
    def __iter__(self) -> Iterator[Chart]: ...
