from collections import UserString
from collections.abc import Iterator

class PlaceholderFormat(UserString):
    @property
    def type(self) -> str: ...
    @property
    def idx(self) -> int: ...

class Placeholder:
    @property
    def idx(self) -> int: ...
    @property
    def placeholder_format(self) -> PlaceholderFormat: ...
    @property
    def name(self) -> str: ...
    def insert_text(self, text: str, **style_kwargs: object) -> None: ...
    def insert_picture(
        self,
        image_path: str,
        bounds: tuple[float, float, float, float] | None = None,
    ) -> None: ...

class TitlePlaceholder(Placeholder): ...
class BodyPlaceholder(Placeholder): ...
class PicturePlaceholder(Placeholder): ...
class ChartPlaceholder(Placeholder): ...
class TablePlaceholder(Placeholder): ...

class PlaceholderCollection:
    def __iter__(self) -> Iterator[Placeholder]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Placeholder: ...
    def get(
        self, idx: int, default: Placeholder | None = None
    ) -> Placeholder | None: ...
    def __call__(self) -> list[Placeholder]: ...
