from collections.abc import Iterator

class Cell:
    row: int
    col: int
    @property
    def is_merge_origin(self) -> bool: ...
    @property
    def is_spanned(self) -> bool: ...
    @property
    def row_span(self) -> int: ...
    @property
    def col_span(self) -> int: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    def split(self) -> None: ...

class CellRange:
    def merge(self) -> None: ...

class Table:
    @property
    def row_count(self) -> int: ...
    @property
    def col_count(self) -> int: ...
    def __getitem__(self, idx: tuple[int | slice, int | slice]) -> Cell | CellRange: ...
    def cell(self, row: int, col: int) -> Cell: ...
    def iter_cells(self) -> Iterator[Cell]: ...
    @property
    def header_row_enabled(self) -> bool: ...
    @header_row_enabled.setter
    def header_row_enabled(self, value: bool) -> None: ...
    @property
    def banded_rows_enabled(self) -> bool: ...
    @banded_rows_enabled.setter
    def banded_rows_enabled(self, value: bool) -> None: ...
    @property
    def first_row(self) -> bool: ...
    @first_row.setter
    def first_row(self, value: bool) -> None: ...
    @property
    def horz_banding(self) -> bool: ...
    @horz_banding.setter
    def horz_banding(self, value: bool) -> None: ...
    @property
    def first_col(self) -> bool: ...
    @first_col.setter
    def first_col(self, value: bool) -> None: ...
    @property
    def last_col(self) -> bool: ...
    @last_col.setter
    def last_col(self, value: bool) -> None: ...
    @property
    def last_row(self) -> bool: ...
    @last_row.setter
    def last_row(self, value: bool) -> None: ...
    @property
    def vert_banding(self) -> bool: ...
    @vert_banding.setter
    def vert_banding(self, value: bool) -> None: ...
    def apply_style(self, style_guid: str) -> None: ...
