from collections.abc import Iterator

class SlideLayout:
    @property
    def part(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def slide_master(self) -> SlideMaster: ...

class SlideLayouts:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> SlideLayout: ...
    def __iter__(self) -> Iterator[SlideLayout]: ...
    def get_by_name(self, name: str) -> SlideLayout | None: ...

class SlideMaster:
    @property
    def part(self) -> str: ...
    @property
    def slide_layouts(self) -> SlideLayouts: ...

class SlideMasters:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> SlideMaster: ...
    def __iter__(self) -> Iterator[SlideMaster]: ...
