from collections.abc import Iterator

class NotesRun:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...

class NotesRunCollection:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NotesRun]: ...
    def __getitem__(self, index: int) -> NotesRun: ...
    def add_run(self, text: str = "") -> NotesRun: ...

class NotesParagraph:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def runs(self) -> NotesRunCollection: ...
    def add_run(self, text: str = "") -> NotesRun: ...

class NotesParagraphCollection:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NotesParagraph]: ...
    def __getitem__(self, index: int) -> NotesParagraph: ...
    def add_paragraph(self, text: str = "") -> NotesParagraph: ...

class NotesTextFrame:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> NotesParagraphCollection: ...
    def clear(self) -> None: ...
    def add_paragraph(self, text: str = "") -> NotesParagraph: ...

class NotesShape:
    @property
    def placeholder_type(self) -> str: ...
    @property
    def idx(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def is_placeholder(self) -> bool: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def cx(self) -> float: ...
    @property
    def cy(self) -> float: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def text_frame(self) -> NotesTextFrame | None: ...

class NotesShapeCollection:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NotesShape]: ...
    def __getitem__(self, index: int) -> NotesShape: ...
    def get(
        self,
        *,
        idx: int | None = None,
        placeholder_type: str | None = None,
        name: str | None = None,
    ) -> NotesShape | None: ...

class NotesSlide:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def placeholders(self) -> list[dict[str, object]]: ...
    @property
    def shapes(self) -> NotesShapeCollection: ...
    @property
    def body_shape(self) -> NotesShape | None: ...
    @property
    def notes_text_frame(self) -> NotesTextFrame | None: ...
