from collections import UserString
from collections.abc import Iterator, Mapping
from types import TracebackType

from typing_extensions import Self

from .constants import ConnectorType, PlaceholderType, ShapeType
from .schemas import (
    Author,
    BatchCommand,
    BatchItemResult,
    ChartDataUpdate,
    ChartSelector,
    ChartState,
    Comment,
    CoreProperties,
    Hyperlink,
    ImageCrop,
    ImageMetadata,
    PresentationMetadata,
    Section,
    Shape,
    ShapeProps,
    ShapeSearchQuery,
    ShapeSearchResult,
    ShapeUpdate,
    SlideChartRef,
    SlideLayoutInfo,
    SlideMasterCloneResult,
    SlideMetadata,
    TableCellInfo,
    TableInfo,
    TextFrame,
    TextRun,
)
from .schemas_shape_types import SlideImageRef

class GopptxError(Exception):
    code: str | None
    def __init__(self, message: str, code: str | None = None) -> None: ...

class Cell:
    row: int
    col: int
    @property
    def is_merge_origin(self) -> bool: ...
    @property
    def is_spanned(self) -> bool: ...
    @property
    def row_span(self) -> int: ...
    @property
    def col_span(self) -> int: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    def split(self) -> None: ...

class CellRange:
    def merge(self) -> None: ...

class Table:
    @property
    def row_count(self) -> int: ...
    @property
    def col_count(self) -> int: ...
    def __getitem__(self, idx: tuple[int | slice, int | slice]) -> Cell | CellRange: ...
    def cell(self, row: int, col: int) -> Cell: ...
    def iter_cells(self) -> Iterator[Cell]: ...
    @property
    def header_row_enabled(self) -> bool: ...
    @header_row_enabled.setter
    def header_row_enabled(self, value: bool) -> None: ...
    @property
    def banded_rows_enabled(self) -> bool: ...
    @banded_rows_enabled.setter
    def banded_rows_enabled(self, value: bool) -> None: ...
    @property
    def first_row(self) -> bool: ...
    @first_row.setter
    def first_row(self, value: bool) -> None: ...
    @property
    def horz_banding(self) -> bool: ...
    @horz_banding.setter
    def horz_banding(self, value: bool) -> None: ...
    @property
    def first_col(self) -> bool: ...
    @first_col.setter
    def first_col(self, value: bool) -> None: ...
    @property
    def last_col(self) -> bool: ...
    @last_col.setter
    def last_col(self, value: bool) -> None: ...
    @property
    def last_row(self) -> bool: ...
    @last_row.setter
    def last_row(self, value: bool) -> None: ...
    @property
    def vert_banding(self) -> bool: ...
    @vert_banding.setter
    def vert_banding(self, value: bool) -> None: ...
    def apply_style(self, style_guid: str) -> None: ...

class FreeformBuilder:
    def move_to(self, x: float, y: float) -> FreeformBuilder: ...
    def add_line_to(self, x: float, y: float) -> FreeformBuilder: ...
    def add_line_segments(
        self, points: list[tuple[float, float]]
    ) -> FreeformBuilder: ...
    def convert_to_shape(self, *, close: bool = False, **kwargs: object) -> int: ...

class CategorySeries:
    name: str
    values: list[float]

class CategoryChartData:
    categories: list[str]
    series: list[CategorySeries]
    def add_category(self, value: str) -> None: ...
    def add_series(self, name: str, values: list[float]) -> None: ...
    def to_add_chart_args(
        self,
    ) -> tuple[list[str], list[float] | list[dict[str, object]]]: ...
    def to_update_payload(self) -> dict[str, object]: ...

class XySeries:
    name: str
    x_values: list[float]
    y_values: list[float]
    sizes: list[float] | None

class XyChartData:
    series: list[XySeries]
    def add_series(
        self,
        name: str,
        x_values: list[float],
        y_values: list[float],
        sizes: list[float] | None = None,
    ) -> None: ...
    def to_update_payload(self) -> dict[str, object]: ...
    def to_add_chart_args(
        self,
    ) -> tuple[list[str], list[float] | list[dict[str, object]]]: ...

class RunHyperlink:
    address: str | None
    action: str | None
    tooltip: str | None
    target_slide: int | None
    jump: str | None
    macro: str | None
    history: bool | None
    highlight_click: bool | None
    end_sound: bool | None
    def __init__(
        self,
        *,
        address: str | None = None,
        action: str | None = None,
        tooltip: str | None = None,
        target_slide: int | None = None,
        jump: str | None = None,
        macro: str | None = None,
        history: bool | None = None,
        highlight_click: bool | None = None,
        end_sound: bool | None = None,
    ) -> None: ...
    def to_payload(self) -> dict[str, object]: ...

class Run:
    text: str
    bold: bool | None
    italic: bool | None
    underline: str | None
    strikethrough: bool | None
    subscript: bool | None
    superscript: bool | None
    color: str | None
    highlight: str | None
    font: str | None
    size_pt: int | None
    code: bool | None
    all_caps: bool | None
    small_caps: bool | None
    @property
    def hyperlink(self) -> Mapping[str, object] | RunHyperlink | None: ...
    @hyperlink.setter
    def hyperlink(self, value: Mapping[str, object] | RunHyperlink | None) -> None: ...
    @property
    def hover_action(self) -> Mapping[str, object] | RunHyperlink | None: ...
    @hover_action.setter
    def hover_action(
        self, value: Mapping[str, object] | RunHyperlink | None
    ) -> None: ...
    def __init__(
        self,
        text: str = "",
        *,
        bold: bool | None = None,
        italic: bool | None = None,
        underline: str | None = None,
        strikethrough: bool | None = None,
        subscript: bool | None = None,
        superscript: bool | None = None,
        color: str | None = None,
        highlight: str | None = None,
        font: str | None = None,
        size_pt: int | None = None,
        code: bool | None = None,
        all_caps: bool | None = None,
        small_caps: bool | None = None,
        hyperlink: Hyperlink | RunHyperlink | None = None,
        hover_action: Hyperlink | RunHyperlink | None = None,
    ) -> None: ...
    def to_payload(self) -> dict[str, object]: ...

class TextFrameProps:
    margin_top: int | None
    margin_bottom: int | None
    margin_left: int | None
    margin_right: int | None
    word_wrap: bool | None
    auto_fit: bool | None
    auto_fit_type: str | None
    vertical_align: str | None
    orientation: str | None
    columns: int | None
    rotation: float | None
    def __init__(
        self,
        *,
        margin_top: int | None = None,
        margin_bottom: int | None = None,
        margin_left: int | None = None,
        margin_right: int | None = None,
        word_wrap: bool | None = None,
        auto_fit: bool | None = None,
        auto_fit_type: str | None = None,
        vertical_align: str | None = None,
        orientation: str | None = None,
        columns: int | None = None,
        rotation: float | None = None,
        vertical_anchor: str | None = None,
        auto_size: str | None = None,
        text_direction: str | None = None,
        column_count: int | None = None,
        text_rotation: float | None = None,
    ) -> None: ...
    def to_payload(self) -> dict[str, object]: ...

class ParagraphProps:
    indent: int | None
    hanging: int | None
    tab_stops: list[int] | None
    alignment: str | None
    bullet_style: str | None
    bullet_char: str | None
    bullet_color: str | None
    bullet_size_pct: int | None
    level: int | None
    line_spacing_pct: int | None
    line_spacing_pts: int | None
    space_before_pts: int | None
    space_after_pts: int | None
    def __init__(
        self,
        *,
        indent: int | None = None,
        hanging: int | None = None,
        tab_stops: list[int] | None = None,
        left_margin: int | None = None,
        hanging_indent: int | None = None,
        alignment: str | None = None,
        bullet_style: str | None = None,
        bullet_char: str | None = None,
        bullet_color: str | None = None,
        bullet_size_pct: int | None = None,
        level: int | None = None,
        line_spacing_pct: int | None = None,
        line_spacing_pts: int | None = None,
        space_before_pts: int | None = None,
        space_after_pts: int | None = None,
        tabs: list[int] | None = None,
    ) -> None: ...
    def to_payload(self) -> dict[str, object]: ...

class Slide:
    def __init__(self, presentation: Presentation, metadata: SlideMetadata) -> None: ...
    @property
    def index(self) -> int: ...
    @property
    def slide_id(self) -> int: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def notes(self) -> str: ...
    @notes.setter
    def notes(self, value: str) -> None: ...
    @property
    def notes_slide(self) -> NotesSlide | None: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    def get_placeholder(self, idx: int) -> Placeholder | None: ...
    def add_shape(
        self,
        shape_type: ShapeType,
        bounds: tuple[float, float, float, float],
        *,
        text: str = "",
        runs: list[TextRun | Run] | None = None,
        text_frame: TextFrame | TextFrameProps | None = None,
        click_action: Hyperlink | None = None,
        **kwargs: str | ShapeProps,
    ) -> int: ...
    def add_textbox(
        self,
        left: float,
        top: float,
        width: float,
        height: float,
        *,
        text: str = "",
        **kwargs: str | ShapeProps,
    ) -> int: ...
    def add_paragraph(
        self,
        paragraph: str,
        *,
        bounds: tuple[float, float, float, float] | None = None,
        gap_emu: int | None = None,
    ) -> int: ...
    def add_textboxes(
        self,
        textboxes: list[dict[str, float | str]],
    ) -> list[int]: ...
    def add_connector(
        self,
        connector_type: ConnectorType,
        begin_x: float,
        begin_y: float,
        end_x: float,
        end_y: float,
        **kwargs: str | ShapeProps,
    ) -> int: ...
    def add_group_shape(self, shapes: list[int] | None = None) -> int: ...
    def build_freeform(
        self,
        start_x: float = 0,
        start_y: float = 0,
        scale: tuple[float, float] | float = 1.0,
    ) -> FreeformBuilder: ...
    def add_table(
        self, rows: int, cols: int, bounds: tuple[int, int, int, int]
    ) -> int: ...
    def get_table(self, shape_id: int) -> TableInfo: ...
    def table(self, shape_id: int) -> Table: ...
    def set_table_flags(self, shape_id: int, flags: dict[str, bool]) -> None: ...
    def set_table_cell_text(
        self, shape_id: int, row: int, col: int, text: str
    ) -> None: ...
    def get_table_cell(self, shape_id: int, row: int, col: int) -> TableCellInfo: ...
    def merge_table_cells(
        self, shape_id: int, cell_range: tuple[int, int, int, int]
    ) -> None: ...
    def split_table_cell(self, shape_id: int, row: int, col: int) -> None: ...
    def set_table_style(self, shape_id: int, style_guid: str) -> None: ...
    def add_image(
        self, path: str, bounds: tuple[float, float, float, float]
    ) -> int: ...
    def remove_shape(self, shape_id: int) -> None: ...
    def clear_shapes(self) -> int: ...
    def update_shape(self, shape_id: int, updates: ShapeUpdate) -> None: ...
    def update_shape_run_texts(
        self,
        updates: list[tuple[int, int, str]] | list[dict[str, object]],
    ) -> None: ...
    def list_shapes(self) -> list[Shape]: ...
    def shape_center(self, shape_id: int) -> tuple[float, float]: ...
    def list_charts(self) -> list[SlideChartRef]: ...
    @property
    def charts(self) -> ChartCollection: ...
    def add_chart(
        self,
        chart_type: str,
        categories: list[str],
        values_or_series: list[float] | list[dict[str, str | list[float]]],
        **kwargs: str | tuple[float, float, float, float],
    ) -> int: ...
    def add_combo_chart(
        self,
        categories: list[str],
        bar_series: list[dict[str, object]],
        line_series: list[dict[str, object]],
        *,
        title: str = ...,
        bounds: tuple[float, float, float, float] = ...,
    ) -> int: ...
    def update(
        self,
        title: str | None = None,
        layout: str | None = None,
        bullets: list[str] | None = None,
    ) -> None: ...
    def add_mermaid(self, diagram: str, *, theme: str = "") -> tuple[int, int]: ...
    def add_smartart(
        self,
        layout: str,
        items: list[str],
        bounds: tuple[float, float, float, float],
    ) -> int: ...
    def add_animation(
        self,
        shape_id: int,
        effect: str,
        *,
        trigger: str = ...,
        duration_ms: int = ...,
        delay_ms: int = ...,
    ) -> None: ...
    def set_transition(
        self,
        transition_type: str,
        *,
        duration_ms: int = ...,
        advance_ms: int | None = ...,
        disable_advance_on_click: bool = ...,
    ) -> None: ...
    def update_smartart(self, shape_id: int, items: list[str]) -> None: ...
    def set_background(
        self,
        bg_type: str,
        *,
        color: str = ...,
        colors: list[str] | None = ...,
        angle: int = ...,
        image_path: str = ...,
        image_data: str = ...,
        color_ref: str = ...,
    ) -> None: ...
    def set_header_footer(
        self,
        *,
        footer: str = ...,
        show_footer: bool = ...,
        show_slide_num: bool = ...,
        show_date_time: bool = ...,
        date_time_text: str = ...,
    ) -> None: ...
    def remove(self) -> None: ...
    def duplicate(self, insert_at: int | None = None) -> Slide: ...

class SlideLayout:
    @property
    def part(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def slide_master(self) -> SlideMaster: ...

class SlideLayouts:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> SlideLayout: ...
    def __iter__(self) -> Iterator[SlideLayout]: ...
    def get_by_name(self, name: str) -> SlideLayout | None: ...

class SlideMaster:
    @property
    def part(self) -> str: ...
    @property
    def slide_layouts(self) -> SlideLayouts: ...

class SlideMasters:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> SlideMaster: ...
    def __iter__(self) -> Iterator[SlideMaster]: ...

class DataLabels:
    @property
    def show_value(self) -> bool: ...
    @show_value.setter
    def show_value(self, value: bool) -> None: ...
    @property
    def show_category_name(self) -> bool: ...
    @show_category_name.setter
    def show_category_name(self, value: bool) -> None: ...

class ChartPlot:
    @property
    def data_labels_visible(self) -> bool: ...
    @data_labels_visible.setter
    def data_labels_visible(self, value: bool) -> None: ...
    @property
    def data_labels(self) -> DataLabels: ...

class ChartPlots:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ChartPlot: ...
    def __iter__(self) -> Iterator[ChartPlot]: ...

class ChartTitle:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...

class ChartLegend:
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def position(self) -> str: ...
    @position.setter
    def position(self, value: str) -> None: ...
    @property
    def include_in_layout(self) -> bool: ...
    @include_in_layout.setter
    def include_in_layout(self, value: bool) -> None: ...

class ChartAxis:
    @property
    def present(self) -> bool: ...
    @property
    def tick_label_position(self) -> str | None: ...
    @tick_label_position.setter
    def tick_label_position(self, value: str) -> None: ...
    @property
    def major_gridlines_visible(self) -> bool: ...
    @major_gridlines_visible.setter
    def major_gridlines_visible(self, value: bool) -> None: ...
    @property
    def crosses(self) -> str | None: ...
    @crosses.setter
    def crosses(self, value: str) -> None: ...

class ChartScene3D:
    @property
    def camera_preset(self) -> str | None: ...
    @camera_preset.setter
    def camera_preset(self, value: str) -> None: ...
    @property
    def camera_field_of_view(self) -> int | None: ...
    @camera_field_of_view.setter
    def camera_field_of_view(self, value: int) -> None: ...
    @property
    def light_rig(self) -> str | None: ...
    @light_rig.setter
    def light_rig(self, value: str) -> None: ...
    @property
    def light_direction(self) -> str | None: ...
    @light_direction.setter
    def light_direction(self, value: str) -> None: ...
    @property
    def light_rig_revolution(self) -> bool | None: ...
    @light_rig_revolution.setter
    def light_rig_revolution(self, value: bool) -> None: ...
    def update(
        self,
        *,
        camera_preset: str,
        light_rig: str,
        light_direction: str,
        camera_field_of_view: int | None = None,
        light_rig_revolution: bool | None = None,
    ) -> None: ...

class ChartArea:
    @property
    def scene3d(self) -> ChartScene3D: ...

class ChartSeries:
    @property
    def name(self) -> str | None: ...
    @property
    def values(self) -> list[float]: ...

class ChartSeriesCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ChartSeries: ...
    def __iter__(self) -> Iterator[ChartSeries]: ...

class Chart:
    @property
    def index(self) -> int: ...
    @property
    def rel_id(self) -> str: ...
    @property
    def chart_part(self) -> str: ...
    @property
    def chart_title(self) -> ChartTitle: ...
    @property
    def title_visible(self) -> bool: ...
    @title_visible.setter
    def title_visible(self, value: bool) -> None: ...
    @property
    def legend(self) -> ChartLegend: ...
    @property
    def plots(self) -> ChartPlots: ...
    @property
    def chart_area(self) -> ChartArea: ...
    @property
    def category_axis(self) -> ChartAxis: ...
    @property
    def value_axis(self) -> ChartAxis: ...
    @property
    def chart_style(self) -> int | None: ...
    @property
    def series(self) -> ChartSeriesCollection: ...
    def replace_data(
        self,
        data: CategoryChartData | XyChartData | ChartDataUpdate,
    ) -> None: ...

class ChartCollection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Chart: ...
    def __iter__(self) -> Iterator[Chart]: ...

class NotesSlide:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def placeholders(self) -> list[dict[str, object]]: ...
    @property
    def shapes(self) -> NotesShapeCollection: ...
    @property
    def body_shape(self) -> NotesShape | None: ...
    @property
    def notes_text_frame(self) -> NotesTextFrame | None: ...

class NotesShape:
    @property
    def placeholder_type(self) -> str: ...
    @property
    def idx(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def is_placeholder(self) -> bool: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def cx(self) -> float: ...
    @property
    def cy(self) -> float: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def text_frame(self) -> NotesTextFrame | None: ...

class NotesTextFrame:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> NotesParagraphCollection: ...
    def clear(self) -> None: ...
    def add_paragraph(self, text: str = "") -> NotesParagraph: ...

class NotesRun:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...

class NotesRunCollection:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NotesRun]: ...
    def __getitem__(self, index: int) -> NotesRun: ...
    def add_run(self, text: str = "") -> NotesRun: ...

class NotesParagraph:
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def runs(self) -> NotesRunCollection: ...
    def add_run(self, text: str = "") -> NotesRun: ...

class NotesParagraphCollection:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NotesParagraph]: ...
    def __getitem__(self, index: int) -> NotesParagraph: ...
    def add_paragraph(self, text: str = "") -> NotesParagraph: ...

class NotesShapeCollection:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NotesShape]: ...
    def __getitem__(self, index: int) -> NotesShape: ...
    def get(
        self,
        *,
        idx: int | None = None,
        placeholder_type: str | None = None,
        name: str | None = None,
    ) -> NotesShape | None: ...

class PlaceholderFormat(UserString):
    @property
    def type(self) -> str: ...
    @property
    def idx(self) -> int: ...

class Placeholder:
    @property
    def idx(self) -> int: ...
    @property
    def placeholder_format(self) -> PlaceholderFormat: ...
    @property
    def name(self) -> str: ...
    def insert_text(self, text: str, **style_kwargs: object) -> None: ...
    def insert_picture(
        self,
        image_path: str,
        bounds: tuple[float, float, float, float] | None = None,
    ) -> None: ...

class TitlePlaceholder(Placeholder): ...
class BodyPlaceholder(Placeholder): ...
class PicturePlaceholder(Placeholder): ...
class ChartPlaceholder(Placeholder): ...
class TablePlaceholder(Placeholder): ...

class PlaceholderCollection:
    def __iter__(self) -> Iterator[Placeholder]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Placeholder: ...
    def get(
        self, idx: int, default: Placeholder | None = None
    ) -> Placeholder | None: ...
    def __call__(self) -> list[Placeholder]: ...

class Slides:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Slide]: ...
    def __getitem__(self, index: int | slice) -> Slide | list[Slide]: ...
    def find_by_slide_id(self, slide_id: int) -> Slide | None: ...

class Presentation:
    _lib: object
    _handle: int | None

    def __init__(self, path: str | None = None) -> None: ...
    @classmethod
    def new(cls, title: str) -> Presentation: ...
    def execute(
        self, op: str, payload: dict[str, object] | None = None
    ) -> dict[str, object]: ...
    def execute_batch(
        self, commands: list[BatchCommand], *, stop_on_error: bool = False
    ) -> list[BatchItemResult]: ...
    @property
    def slide_count(self) -> int: ...
    @property
    def metadata(self) -> PresentationMetadata: ...
    @property
    def slides(self) -> Slides: ...
    @property
    def slides_metadata(self) -> list[SlideMetadata]: ...
    @property
    def sections(self) -> list[Section]: ...
    @property
    def slide_masters(self) -> SlideMasters: ...
    def add_slide(
        self,
        title: str,
        layout: str | None = None,
        bullets: list[str] | None = None,
    ) -> Slide: ...
    def remove_slide(self, index: int) -> None: ...
    def move_slide(self, from_index: int, to_index: int) -> None: ...
    def duplicate_slide(self, index: int, insert_at: int | None = None) -> int: ...
    def update_slide(
        self,
        index: int,
        title: str | None = None,
        layout: str | None = None,
        bullets: list[str] | None = None,
    ) -> None: ...
    def add_chart(
        self,
        slide_index: int,
        chart_type: str,
        categories: list[str],
        values_or_series: list[float] | list[dict[str, str | list[float]]],
        **kwargs: str | tuple[float, float, float, float],
    ) -> int: ...
    def add_table(
        self,
        slide_index: int,
        rows: int,
        cols: int,
        bounds: tuple[int, int, int, int],
    ) -> int: ...
    def get_table(self, slide_index: int, shape_id: int) -> TableInfo: ...
    def set_table_flags(
        self, slide_index: int, shape_id: int, flags: dict[str, bool]
    ) -> None: ...
    def set_table_cell_text(
        self, slide_index: int, shape_id: int, row: int, col: int, text: str
    ) -> None: ...
    def get_table_cell(
        self, slide_index: int, shape_id: int, row: int, col: int
    ) -> TableCellInfo: ...
    def merge_table_cells(
        self, slide_index: int, shape_id: int, cell_range: tuple[int, int, int, int]
    ) -> None: ...
    def split_table_cell(
        self, slide_index: int, shape_id: int, row: int, col: int
    ) -> None: ...
    def set_table_style(
        self, slide_index: int, shape_id: int, style_guid: str
    ) -> None: ...
    def define_table_style(self, name: str, style_id: str | None = None) -> str: ...
    def list_table_styles(self) -> list[dict[str, str]]: ...
    def set_slide_title(self, index: int, title: str) -> None: ...
    def find_and_replace(self, find_text: str, replace_text: str) -> int: ...
    def search_shapes(
        self, query: ShapeSearchQuery | str
    ) -> list[ShapeSearchResult]: ...
    def get_authors(self) -> list[Author]: ...
    def add_author(self, name: str, initials: str) -> int: ...
    def get_comments(self, slide_index: int) -> list[Comment]: ...
    def add_comment(
        self, slide_index: int, author_id: int, text: str, x: int = 0, y: int = 0
    ) -> int: ...
    def remove_comment(
        self,
        slide_index_or_index: int,
        author_id: int | None = None,
        author_index: int | None = None,
    ) -> None: ...
    def add_section(self, name: str, slide_indices: list[int]) -> None: ...
    def remove_section(self, name: str) -> None: ...
    def rename_section(self, old_name: str, new_name: str) -> None: ...
    @property
    def core_properties(self) -> CoreProperties: ...
    @core_properties.setter
    def core_properties(self, props: CoreProperties) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def author(self) -> str: ...
    @author.setter
    def author(self, value: str) -> None: ...
    @property
    def comments(self) -> str: ...
    @comments.setter
    def comments(self, value: str) -> None: ...
    @property
    def identifier(self) -> str: ...
    @identifier.setter
    def identifier(self, value: str) -> None: ...
    @property
    def language(self) -> str: ...
    @language.setter
    def language(self, value: str) -> None: ...
    @property
    def last_printed(self) -> str: ...
    @last_printed.setter
    def last_printed(self, value: str) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, value: str) -> None: ...
    def add_title_slide(self, title: str) -> Slide: ...
    def add_bullet_slide(self, title: str, bullets: list[str]) -> Slide: ...
    def add_paragraph_slide(
        self,
        title: str,
        paragraph: str,
        *,
        bounds: tuple[float, float, float, float] | None = None,
        layout: str | None = None,
    ) -> Slide: ...
    def add_slide_from_markdown(self, markdown: str, *, layout: str = "") -> int: ...
    def add_slide_from_url(self, url: str, *, layout: str = "") -> int: ...
    def __getitem__(self, index: int | slice) -> Slide | list[Slide]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Slide]: ...
    def apply_theme(self, theme_name: str) -> None: ...
    def set_slide_size(self, width: int, height: int) -> None: ...
    def list_slide_layouts(self) -> list[SlideLayoutInfo]: ...
    def rebind_slide_layout(self, slide_index: int, layout_part: str) -> None: ...
    def clone_layout_master_family(
        self, layout_part: str
    ) -> SlideMasterCloneResult: ...
    def list_shapes(self, slide_index: int) -> list[Shape]: ...
    def add_shape(
        self,
        slide_index: int,
        shape_type: ShapeType,
        bounds: tuple[float, float, float, float],
        **kwargs: str | ShapeProps,
    ) -> int: ...
    def add_textbox(
        self,
        slide_index: int,
        left: float,
        top: float,
        width: float,
        height: float,
        *,
        text: str = "",
        **kwargs: str | ShapeProps,
    ) -> int: ...
    def add_textboxes(
        self,
        slide_index: int,
        textboxes: list[dict[str, float | str]],
    ) -> list[int]: ...
    def add_connector(
        self,
        slide_index: int,
        connector_type: ConnectorType,
        begin_x: float,
        begin_y: float,
        end_x: float,
        end_y: float,
        **kwargs: str | ShapeProps,
    ) -> int: ...
    def add_group_shape(
        self, slide_index: int, shapes: list[int] | None = None
    ) -> int: ...
    def build_freeform(
        self,
        slide_index: int,
        start_x: float = 0,
        start_y: float = 0,
        scale: tuple[float, float] | float = 1.0,
    ) -> FreeformBuilder: ...
    def add_image(
        self,
        slide_index: int,
        source: str | bytes,
        bounds: tuple[float, float, float, float],
        *,
        name: str = "",
        crop: ImageCrop | None = None,
        rotation: float | None = None,
        flip_h: bool | None = None,
        flip_v: bool | None = None,
        **kwargs: object,
    ) -> int: ...
    def add_video(
        self,
        slide_index: int,
        source: str | bytes,
        bounds: tuple[float, float, float, float],
        *,
        name: str = "",
        poster_frame: str | bytes | None = None,
        **kwargs: object,
    ) -> int: ...
    def add_ole_object(
        self,
        slide_index: int,
        source: str | bytes,
        bounds: tuple[float, float, float, float],
        *,
        name: str = "",
        prog_id: str = "",
        icon: str | bytes | None = None,
        **kwargs: object,
    ) -> int: ...
    def get_image_metadata(
        self,
        slide_index: int,
        shape_id: int,
    ) -> ImageMetadata: ...
    def remove_shape(self, slide_index: int, shape_id: int) -> None: ...
    def get_shape_center(
        self, slide_index: int, shape_id: int
    ) -> tuple[float, float]: ...
    def clear_shapes(self, slide_index: int) -> int: ...
    def update_shape(
        self, slide_index: int, shape_id: int, updates: ShapeUpdate
    ) -> None: ...
    def update_slide_run_texts(
        self, slide_index: int, updates: list[dict[str, object]]
    ) -> None: ...
    def update_deck_run_texts(self, slide_updates: list[dict[str, object]]) -> None: ...
    def get_notes(self, slide_index: int) -> str: ...
    def set_notes(self, slide_index: int, text: str) -> None: ...
    def list_slide_charts(self, slide_index: int) -> list[SlideChartRef]: ...
    def get_chart_state(
        self,
        slide_index: int,
        chart_selector: ChartSelector,
    ) -> ChartState: ...
    def get_chart_state_by_index(
        self, slide_index: int, chart_index: int
    ) -> ChartState: ...
    def get_chart_state_by_rel_id(
        self, slide_index: int, rel_id: str
    ) -> ChartState: ...
    def update_chart_data(
        self,
        slide_index: int,
        chart_selector: ChartSelector | list[str],
        data: ChartDataUpdate | list[dict[str, object]],
    ) -> None: ...
    def update_chart_data_by_index(
        self,
        slide_index: int,
        chart_index: int,
        data: ChartDataUpdate,
    ) -> None: ...
    def update_chart_data_by_rel_id(
        self,
        slide_index: int,
        rel_id: str,
        data: ChartDataUpdate,
    ) -> None: ...
    def replace_chart_data_by_index(
        self,
        slide_index: int,
        chart_index: int,
        categories: list[str],
        values: list[float],
    ) -> None: ...
    def replace_chart_data_by_rel_id(
        self,
        slide_index: int,
        rel_id: str,
        categories: list[str],
        values: list[float],
    ) -> None: ...
    def duplicate_slide_after(self, index: int) -> int: ...
    def merge_from_file(self, path: str) -> None: ...
    def merge_from_editor(self, other: Presentation) -> None: ...
    def validate(self) -> list[dict[str, object]]: ...
    def repair(self) -> dict[str, object]: ...
    def convert_to_grayscale(
        self,
        *,
        slides: list[int] | None = ...,
        shapes: list[dict[str, int]] | None = ...,
        text: list[dict[str, object]] | None = ...,
        placeholders: list[dict[str, int | PlaceholderType]] | None = ...,
        colors: bool = ...,
        images: bool = ...,
        backgrounds: bool = ...,
    ) -> None: ...
    def list_slide_images(self, slide_index: int) -> list[SlideImageRef]: ...
    def swap_image_by_index(
        self, slide_index: int, image_index: int, data: bytes, img_format: str
    ) -> None: ...
    def swap_image_by_rel_id(
        self, slide_index: int, rel_id: str, data: bytes, img_format: str
    ) -> None: ...
    def move_shape_to_index(
        self, slide_index: int, shape_id: int, target_index: int
    ) -> None: ...
    def get_layout_shapes(self, layout_part: str) -> list[str]: ...
    def get_master_shapes(self, master_part: str) -> list[str]: ...
    def get_layout_placeholders(self, layout_part: str) -> list[dict[str, object]]: ...
    def get_master_placeholders(self, master_part: str) -> list[dict[str, object]]: ...
    def set_global_theme_preset(self, name: str) -> None: ...
    def set_theme_font_scheme(self, major: str, minor: str) -> None: ...
    def set_theme_color_scheme(self, **colors: str) -> None: ...
    def get_theme_inventory(self) -> dict[str, object]: ...
    def list_notes_shapes(self, slide_index: int) -> list[dict[str, object]]: ...
    def list_notes_placeholders(self, slide_index: int) -> list[dict[str, object]]: ...
    def update_notes_master(
        self,
        *,
        header: str = ...,
        footer: str = ...,
        show_date_time: bool = ...,
        show_slide_num: bool = ...,
    ) -> None: ...
    def get_handout_master(self) -> dict[str, object]: ...
    def update_handout_master(
        self,
        *,
        orientation: str = ...,
        slides_per_page: int = ...,
    ) -> None: ...
    def has_digital_signature(self) -> bool: ...
    def add_smartart(
        self,
        layout: str,
        items: list[str],
        bounds: tuple[float, float, float, float] | None = ...,
    ) -> int: ...
    def add_animation(
        self,
        shape_id: int,
        effect: str,
        *,
        trigger: str = ...,
        duration_ms: int = ...,
        delay_ms: int = ...,
    ) -> None: ...
    def set_transition(
        self,
        transition_type: str,
        *,
        duration_ms: int = ...,
        advance_ms: int = ...,
        disable_advance_on_click: bool = ...,
    ) -> None: ...
    def open(self, path: str) -> None: ...
    def open_bytes(self, data: bytes) -> None: ...
    def save(self, path: str) -> None: ...
    def to_bytes(self) -> bytes: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class ShapeBuilder:
    def __init__(
        self, shape_type: ShapeType, x: float, y: float, w: float, h: float
    ) -> None: ...
    @classmethod
    def of(
        cls, shape_type: ShapeType, x: float, y: float, w: float, h: float
    ) -> ShapeBuilder: ...
    @classmethod
    def rectangle(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def rounded_rectangle(
        cls, x: float, y: float, w: float, h: float
    ) -> ShapeBuilder: ...
    @classmethod
    def ellipse(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def triangle(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def right_triangle(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def diamond(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def pentagon(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def hexagon(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def parallelogram(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def cloud(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def heart(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def star5(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    @classmethod
    def star6(cls, x: float, y: float, w: float, h: float) -> ShapeBuilder: ...
    def with_text(self, text: str) -> ShapeBuilder: ...
    def with_fill(self, color: str) -> ShapeBuilder: ...
    def with_no_fill(self) -> ShapeBuilder: ...
    def with_line(
        self,
        color: str,
        *,
        width_emu: int | None = ...,
        dash_style: str | None = ...,
        start_arrow: str | None = ...,
        start_arrow_width: str | None = ...,
        start_arrow_length: str | None = ...,
        end_arrow: str | None = ...,
        end_arrow_width: str | None = ...,
        end_arrow_length: str | None = ...,
    ) -> ShapeBuilder: ...
    def with_no_line(self) -> ShapeBuilder: ...
    def with_shadow(
        self,
        color: str = ...,
        *,
        blur_emu: int | None = ...,
        distance_emu: int | None = ...,
        angle_deg: float = ...,
    ) -> ShapeBuilder: ...
    def with_rotation(self, degrees: float) -> ShapeBuilder: ...
    def flip_horizontal(self) -> ShapeBuilder: ...
    def flip_vertical(self) -> ShapeBuilder: ...
    @property
    def shape_type(self) -> str: ...
    @property
    def bounds(self) -> tuple[float, float, float, float]: ...
    def to_kwargs(self) -> dict[str, object]: ...

class RunBuilder:
    def __init__(self, text: str = "") -> None: ...
    def text(self, value: str) -> RunBuilder: ...
    def bold(self, *, value: bool = True) -> RunBuilder: ...
    def italic(self, *, value: bool = True) -> RunBuilder: ...
    def underline(self, style: str = "sng") -> RunBuilder: ...
    def strikethrough(self, style: str = "sng") -> RunBuilder: ...
    def subscript(self, *, value: bool = True) -> RunBuilder: ...
    def superscript(self, *, value: bool = True) -> RunBuilder: ...
    def color(self, hex_color: str) -> RunBuilder: ...
    def highlight(self, hex_color: str) -> RunBuilder: ...
    def font(self, name: str) -> RunBuilder: ...
    def size_pt(self, points: int) -> RunBuilder: ...
    def code(self, *, value: bool = True) -> RunBuilder: ...
    def all_caps(self, *, value: bool = True) -> RunBuilder: ...
    def small_caps(self, *, value: bool = True) -> RunBuilder: ...
    def hyperlink(self, address: str, *, tooltip: str = "") -> RunBuilder: ...
    def hover_action(self, address: str) -> RunBuilder: ...
    def build(self) -> TextRun: ...
    def to_payload(self) -> dict[str, object]: ...

class ShapeTextFrame:
    def set_runs(self, builders: list[RunBuilder]) -> None: ...

class ShapeProxy:
    def set_text_runs(self, builders: list[RunBuilder]) -> None: ...

class PresentationBuilder:
    def __init__(self, title: str) -> None: ...
    def with_author(self, author: str) -> PresentationBuilder: ...
    def with_subject(self, subject: str) -> PresentationBuilder: ...
    def with_keywords(self, keywords: str) -> PresentationBuilder: ...
    def with_description(self, description: str) -> PresentationBuilder: ...
    def with_theme(self, theme: str) -> PresentationBuilder: ...
    def with_slide_size(
        self, width_inches: float, height_inches: float
    ) -> PresentationBuilder: ...
    def with_modify_password(self, password: str) -> PresentationBuilder: ...
    def with_mark_as_final(self, *, final: bool = ...) -> PresentationBuilder: ...
    def add_title_slide(self, title: str, layout: str = ...) -> PresentationBuilder: ...
    def add_bullet_slide(
        self, title: str, bullets: list[str], layout: str = ...
    ) -> PresentationBuilder: ...
    def build(self) -> Presentation: ...
    def save(self, path: str) -> None: ...
    def to_bytes(self) -> bytes: ...
