from __future__ import annotations

from typing import Any, Dict, Optional


from .types import PresentationMetadata


class GopptxError(Exception):
    code: Optional[str]
    def __init__(self, message: str, code: Optional[str] = None) -> None: ...


class Presentation:
    _lib: Any
    _handle: Optional[int]

    def __init__(self, path: Optional[str] = None) -> None: ...
    def execute(self, op: str, payload: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    @property
    def slide_count(self) -> int: ...
    @property
    def metadata(self) -> PresentationMetadata: ...
    def add_slide(self, title: str) -> int: ...
    def remove_slide(self, index: int) -> None: ...
    def move_slide(self, from_index: int, to_index: int) -> None: ...
    def duplicate_slide(self, index: int, insert_at: Optional[int] = None) -> int: ...
    def open(self, path: str) -> None: ...
    def save(self, path: str) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Presentation": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
