"""Constants for gopptx library."""

from __future__ import annotations

import sys
from enum import Enum

if sys.version_info >= (3, 11):
    from enum import StrEnum
else:

    class StrEnum(str, Enum):
        """Python 3.10 compatibility shim for ``enum.StrEnum``."""


# Theme Presets
THEME_CORPORATE = "Corporate"
THEME_MODERN = "Modern"
THEME_VIBRANT = "Vibrant"
THEME_DARK = "Dark"
THEME_NATURE = "Nature"
THEME_TECH = "Tech"
THEME_CARBON = "Carbon"

# Shape Types (Representative subset of OOXML presets)
SHAPE_RECTANGLE = "rect"
SHAPE_ROUNDED_RECTANGLE = "roundRect"
SHAPE_ELLIPSE = "ellipse"
SHAPE_TRIANGLE = "triangle"
SHAPE_RIGHT_TRIANGLE = "rtTriangle"
SHAPE_DIAMOND = "diamond"
SHAPE_PENTAGON = "pentagon"
SHAPE_HEXAGON = "hexagon"
SHAPE_PARALLELOGRAM = "parallelogram"
SHAPE_CLOUD = "cloud"
SHAPE_HEART = "heart"
SHAPE_STAR_5 = "star5"
SHAPE_STAR_6 = "star6"
SHAPE_STAR_7 = "star7"
SHAPE_STAR_8 = "star8"
SHAPE_STAR_10 = "star10"
SHAPE_STAR_12 = "star12"
SHAPE_STAR_16 = "star16"
SHAPE_STAR_24 = "star24"
SHAPE_STAR_32 = "star32"

# Flowchart Shapes
SHAPE_FLOWCHART_PROCESS = "flowChartProcess"
SHAPE_FLOWCHART_DECISION = "flowChartDecision"
SHAPE_FLOWCHART_DATA = "flowChartData"
SHAPE_FLOWCHART_PREDEFINED_PROCESS = "flowChartPredefinedProcess"
SHAPE_FLOWCHART_INTERNAL_STORAGE = "flowChartInternalStorage"
SHAPE_FLOWCHART_DOCUMENT = "flowChartDocument"
SHAPE_FLOWCHART_MULTIDOCUMENT = "flowChartMultidocument"
SHAPE_FLOWCHART_TERMINATOR = "flowChartTerminator"
SHAPE_FLOWCHART_PREPARATION = "flowChartPreparation"
SHAPE_FLOWCHART_MANUAL_INPUT = "flowChartManualInput"
SHAPE_FLOWCHART_MANUAL_OPERATION = "flowChartManualOperation"

# Connectors
SHAPE_LINE = "line"
SHAPE_CURVED_CONNECTOR_2 = "curvedConnector2"
SHAPE_CURVED_CONNECTOR_3 = "curvedConnector3"
SHAPE_CURVED_CONNECTOR_4 = "curvedConnector4"
SHAPE_CURVED_CONNECTOR_5 = "curvedConnector5"
SHAPE_BENT_CONNECTOR_2 = "bentConnector2"
SHAPE_BENT_CONNECTOR_3 = "bentConnector3"
SHAPE_BENT_CONNECTOR_4 = "bentConnector4"
SHAPE_BENT_CONNECTOR_5 = "bentConnector5"


class ShapeType(StrEnum):
    """Typed shape tokens for ``add_shape`` calls."""

    RECTANGLE = SHAPE_RECTANGLE
    ROUNDED_RECTANGLE = SHAPE_ROUNDED_RECTANGLE
    ELLIPSE = SHAPE_ELLIPSE
    TRIANGLE = SHAPE_TRIANGLE
    RIGHT_TRIANGLE = SHAPE_RIGHT_TRIANGLE
    DIAMOND = SHAPE_DIAMOND
    PENTAGON = SHAPE_PENTAGON
    HEXAGON = SHAPE_HEXAGON
    PARALLELOGRAM = SHAPE_PARALLELOGRAM
    CLOUD = SHAPE_CLOUD
    HEART = SHAPE_HEART
    STAR_5 = SHAPE_STAR_5
    STAR_6 = SHAPE_STAR_6
    STAR_7 = SHAPE_STAR_7
    STAR_8 = SHAPE_STAR_8
    STAR_10 = SHAPE_STAR_10
    STAR_12 = SHAPE_STAR_12
    STAR_16 = SHAPE_STAR_16
    STAR_24 = SHAPE_STAR_24
    STAR_32 = SHAPE_STAR_32
    FLOWCHART_PROCESS = SHAPE_FLOWCHART_PROCESS
    FLOWCHART_DECISION = SHAPE_FLOWCHART_DECISION
    FLOWCHART_DATA = SHAPE_FLOWCHART_DATA
    FLOWCHART_PREDEFINED_PROCESS = SHAPE_FLOWCHART_PREDEFINED_PROCESS
    FLOWCHART_INTERNAL_STORAGE = SHAPE_FLOWCHART_INTERNAL_STORAGE
    FLOWCHART_DOCUMENT = SHAPE_FLOWCHART_DOCUMENT
    FLOWCHART_MULTIDOCUMENT = SHAPE_FLOWCHART_MULTIDOCUMENT
    FLOWCHART_TERMINATOR = SHAPE_FLOWCHART_TERMINATOR
    FLOWCHART_PREPARATION = SHAPE_FLOWCHART_PREPARATION
    FLOWCHART_MANUAL_INPUT = SHAPE_FLOWCHART_MANUAL_INPUT
    FLOWCHART_MANUAL_OPERATION = SHAPE_FLOWCHART_MANUAL_OPERATION
    LINE = SHAPE_LINE
    CURVED_CONNECTOR_2 = SHAPE_CURVED_CONNECTOR_2
    CURVED_CONNECTOR_3 = SHAPE_CURVED_CONNECTOR_3
    CURVED_CONNECTOR_4 = SHAPE_CURVED_CONNECTOR_4
    CURVED_CONNECTOR_5 = SHAPE_CURVED_CONNECTOR_5
    BENT_CONNECTOR_2 = SHAPE_BENT_CONNECTOR_2
    BENT_CONNECTOR_3 = SHAPE_BENT_CONNECTOR_3
    BENT_CONNECTOR_4 = SHAPE_BENT_CONNECTOR_4
    BENT_CONNECTOR_5 = SHAPE_BENT_CONNECTOR_5


class ConnectorType(StrEnum):
    """Typed connector tokens for ``add_connector`` calls."""

    STRAIGHT = "straight"
    ELBOW = "elbow"
    CURVED = "curved"
    LINE = SHAPE_LINE
    CURVED_CONNECTOR_2 = SHAPE_CURVED_CONNECTOR_2
    CURVED_CONNECTOR_3 = SHAPE_CURVED_CONNECTOR_3
    CURVED_CONNECTOR_4 = SHAPE_CURVED_CONNECTOR_4
    CURVED_CONNECTOR_5 = SHAPE_CURVED_CONNECTOR_5
    BENT_CONNECTOR_2 = SHAPE_BENT_CONNECTOR_2
    BENT_CONNECTOR_3 = SHAPE_BENT_CONNECTOR_3
    BENT_CONNECTOR_4 = SHAPE_BENT_CONNECTOR_4
    BENT_CONNECTOR_5 = SHAPE_BENT_CONNECTOR_5


# Placeholder Types
PLACEHOLDER_TITLE = "title"
PLACEHOLDER_BODY = "body"
PLACEHOLDER_CENTERED_TITLE = "ctrTitle"
PLACEHOLDER_SUBTITLE = "subTitle"
PLACEHOLDER_DATE_TIME = "dt"
PLACEHOLDER_SLIDE_NUMBER = "sldNum"
PLACEHOLDER_FOOTER = "ftr"
PLACEHOLDER_HEADER = "hdr"
PLACEHOLDER_OBJECT = "obj"
PLACEHOLDER_CHART = "chart"
PLACEHOLDER_TABLE = "tbl"
PLACEHOLDER_CLIP_ART = "clipArt"
PLACEHOLDER_DIAGRAM = "dgm"
PLACEHOLDER_MEDIA = "media"
PLACEHOLDER_SLIDE_IMAGE = "sldImg"
PLACEHOLDER_PICTURE = "pic"


class PlaceholderType(StrEnum):
    """Typed placeholder tokens for placeholder-aware APIs."""

    TITLE = PLACEHOLDER_TITLE
    BODY = PLACEHOLDER_BODY
    CENTERED_TITLE = PLACEHOLDER_CENTERED_TITLE
    SUBTITLE = PLACEHOLDER_SUBTITLE
    DATE_TIME = PLACEHOLDER_DATE_TIME
    SLIDE_NUMBER = PLACEHOLDER_SLIDE_NUMBER
    FOOTER = PLACEHOLDER_FOOTER
    HEADER = PLACEHOLDER_HEADER
    OBJECT = PLACEHOLDER_OBJECT
    CHART = PLACEHOLDER_CHART
    TABLE = PLACEHOLDER_TABLE
    CLIP_ART = PLACEHOLDER_CLIP_ART
    DIAGRAM = PLACEHOLDER_DIAGRAM
    MEDIA = PLACEHOLDER_MEDIA
    SLIDE_IMAGE = PLACEHOLDER_SLIDE_IMAGE
    PICTURE = PLACEHOLDER_PICTURE


# Alignment
ALIGN_LEFT = "l"
ALIGN_CENTER = "ctr"
ALIGN_RIGHT = "r"
ALIGN_JUSTIFY = "just"

# Vertical Alignment
VALIGN_TOP = "t"
VALIGN_CENTER = "ctr"
VALIGN_BOTTOM = "b"

# Underline Styles
UNDERLINE_NONE = "none"
UNDERLINE_SINGLE = "sng"
UNDERLINE_DOUBLE = "dbl"
UNDERLINE_DOTTED = "dotted"
UNDERLINE_DASH = "dash"

# Slide Size Constants (EMU)
SIZE_4X3_WIDTH = 9144000
SIZE_4X3_HEIGHT = 6858000
SIZE_16X9_WIDTH = 12192000
SIZE_16X9_HEIGHT = 6858000
