
from typing import FrozenSet, Tuple

OP_ADD_AUTHOR: str
OP_ADD_CHART: str
OP_ADD_COMMENT: str
OP_ADD_IMAGE: str
OP_ADD_SECTION: str
OP_ADD_SHAPE: str
OP_ADD_SLIDE: str
OP_APPLY_THEME: str
OP_BATCH_EXECUTE: str
OP_CLONE_LAYOUT_MASTER_FAMILY: str
OP_DUPLICATE_SLIDE: str
OP_FIND_AND_REPLACE: str
OP_GET_AUTHORS: str
OP_GET_COMMENTS: str
OP_GET_CORE_PROPERTIES: str
OP_GET_METADATA: str
OP_GET_NOTES: str
OP_GET_SECTIONS: str
OP_LIST_MASTER_LAYOUTS: str
OP_LIST_SHAPES: str
OP_LIST_SLIDES: str
OP_LIST_SLIDE_CHARTS: str
OP_LIST_SLIDE_LAYOUTS: str
OP_LIST_SLIDE_MASTERS: str
OP_MERGE_FROM_FILE: str
OP_MOVE_SLIDE: str
OP_REBIND_SLIDE_LAYOUT: str
OP_REMOVE_COMMENT: str
OP_REMOVE_SECTION: str
OP_REMOVE_SHAPE: str
OP_REMOVE_SLIDE: str
OP_RENAME_SECTION: str
OP_SEARCH_SHAPES: str
OP_SET_CORE_PROPERTIES: str
OP_SET_MARK_AS_FINAL: str
OP_SET_MODIFY_PASSWORD: str
OP_SET_NOTES: str
OP_SET_SLIDE_SIZE: str
OP_SET_SLIDE_TITLE: str
OP_SLIDE_COUNT: str
OP_UPDATE_CHART_DATA: str
OP_UPDATE_SHAPE: str
OP_UPDATE_SLIDE: str
SUPPORTED_OPS: Tuple[str, ...]
SUPPORTED_OPS_SET: FrozenSet[str]
