from __future__ import annotations

from typing import Tuple

OP_SLIDE_COUNT: str
OP_ADD_SLIDE: str
OP_REMOVE_SLIDE: str
OP_MOVE_SLIDE: str
OP_DUPLICATE_SLIDE: str
OP_GET_METADATA: str
OP_UPDATE_CHART_DATA: str
OP_LIST_SLIDE_CHARTS: str
OP_LIST_SLIDE_LAYOUTS: str
OP_REBIND_SLIDE_LAYOUT: str
OP_CLONE_LAYOUT_MASTER_FAMILY: str
OP_ADD_SECTION: str
OP_REMOVE_SECTION: str
OP_RENAME_SECTION: str
OP_GET_CORE_PROPERTIES: str
OP_SET_CORE_PROPERTIES: str
OP_APPLY_THEME: str
OP_SET_SLIDE_SIZE: str
OP_LIST_SHAPES: str
OP_ADD_SHAPE: str
OP_REMOVE_SHAPE: str
OP_UPDATE_SHAPE: str
OP_GET_NOTES: str
OP_SET_NOTES: str
SUPPORTED_OPS: Tuple[str, ...]
