// Command gen_smartart_layouts turns the harvested SmartArt layout manifest
// into Go constants, so every layout PowerPoint offers can be named in code.
//
// The manifest lists what PowerPoint itself reports for each layout: its
// gallery name and the URI that identifies it. It is captured from PowerPoint
// rather than written by hand, and is the source this generator reads.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"unicode"
)

type layoutEntry struct {
	Name       string `json:"name"`
	URI        string `json:"uri"`
	Key        string `json:"key"`
	LayoutOnly bool   `json:"layoutOnly"`
}

const (
	expectedArgs = 5
)

const usage = "usage: gen_smartart_layouts <layouts.json> <existing.go> <constants.go> <names.go>"

func main() {
	if len(os.Args) != expectedArgs {
		log.Fatal(usage)
	}
	manifestPath, existingPath := os.Args[1], os.Args[2]
	constantsPath, namesPath := os.Args[3], os.Args[4]

	entries, err := readManifest(manifestPath)
	if err != nil {
		log.Fatal(err)
	}
	existing, err := os.ReadFile(existingPath)
	if err != nil {
		log.Fatal(err)
	}

	// Constants and names are written separately: together they outgrow the
	// repository's per-file ceiling.
	write(constantsPath, renderConstants(entries, string(existing)))
	write(namesPath, renderNames(entries))
}

func write(path, source string) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(path, formatted, 0o600); err != nil {
		log.Fatal(err)
	}
}

func readManifest(path string) ([]layoutEntry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var entries []layoutEntry
	if err := json.Unmarshal(data, &entries); err != nil {
		return nil, err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].URI < entries[j].URI })
	return entries, nil
}

// renderConstants writes a constant per layout, skipping the ones the
// hand-written file already names so that the established names keep their
// place.
func renderConstants(entries []layoutEntry, existing string) string {
	var b strings.Builder
	b.WriteString("// Code generated by gen_smartart_layouts. DO NOT EDIT.\n\n")
	b.WriteString("package smartart\n\n")
	b.WriteString("// The layouts PowerPoint offers, named as its gallery names them.\n")
	b.WriteString("const (\n")

	seen := map[string]bool{}
	for _, entry := range entries {
		if strings.Contains(existing, `"`+entry.URI+`"`) {
			continue
		}
		name := goName(entry.Name)
		if name == "" || seen[name] || strings.Contains(existing, "\t"+name+" Layout") {
			continue
		}
		seen[name] = true
		fmt.Fprintf(&b, "\t// %s is PowerPoint's %q layout.\n", name, entry.Name)
		fmt.Fprintf(&b, "\t%s Layout = %q\n", name, entry.URI)
	}
	b.WriteString(")\n")
	return b.String()
}

// renderNames writes the gallery name of each layout.
func renderNames(entries []layoutEntry) string {
	var b strings.Builder
	b.WriteString("// Code generated by gen_smartart_layouts. DO NOT EDIT.\n\n")
	b.WriteString("package smartart\n\n")
	b.WriteString("// layoutDisplayNames gives each layout the name it has in the gallery.\n")
	b.WriteString("//\n")
	b.WriteString("//nolint:gochecknoglobals // generated lookup table\n")
	b.WriteString("var layoutDisplayNames = map[Layout]string{\n")
	for _, entry := range entries {
		fmt.Fprintf(&b, "\t%q: %q,\n", entry.URI, entry.Name)
	}
	b.WriteString("}\n")
	return b.String()
}

// goName turns a gallery name into an exported Go identifier.
func goName(display string) string {
	var b strings.Builder
	upcomingUpper := true
	for _, r := range display {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			if upcomingUpper {
				b.WriteRune(unicode.ToUpper(r))
				upcomingUpper = false
				continue
			}
			b.WriteRune(r)
		default:
			upcomingUpper = true
		}
	}
	name := b.String()
	if name == "" || unicode.IsDigit(rune(name[0])) {
		return ""
	}
	return name
}
