// Code generated by cmd/gen_slide_builder. DO NOT EDIT.

package elements

// SlideBuilder builds a SlideContent through pointer-receiver methods.
//
// SlideContent's own chainable methods take a value receiver, so dropping the
// returned value silently discards the change and the compiler says nothing:
//
//	s := NewSlide("t")
//	s.AddBullet("lost") // no effect
//
// SlideBuilder mutates in place, so the same mistake is impossible:
//
//	b := NewSlideBuilder("t")
//	b.AddBullet("kept") // applied
//	slide := b.Build()
//
// Every method returns the builder, so calls still chain.
type SlideBuilder struct {
	content SlideContent
}

// NewSlideBuilder starts a builder for a slide with the given title.
func NewSlideBuilder(title string) *SlideBuilder {
	return &SlideBuilder{content: NewSlide(title)}
}

// BuildFrom starts a builder from an existing SlideContent, so code already
// holding one can switch to the pointer-receiver style.
func BuildFrom(content SlideContent) *SlideBuilder {
	return &SlideBuilder{content: content}
}

// Build returns the SlideContent assembled so far.
func (b *SlideBuilder) Build() SlideContent {
	return b.content
}
