// Code generated by cmd/gen_slide_builder. DO NOT EDIT.

package elements

import (
	"github.com/djinn-soul/gopptx/pkg/pptx/transitions"
)

// WithTransition sets the transition for the slide.
func (b *SlideBuilder) WithTransition(t transitions.SlideTransition) *SlideBuilder {
	b.content = b.content.WithTransition(t)
	return b
}

// WithTransitionOptions sets built-in transition options.
func (b *SlideBuilder) WithTransitionOptions(opt transitions.TransitionOptions) *SlideBuilder {
	b.content = b.content.WithTransitionOptions(opt)
	return b
}

// WithTransitionSound sets a sound file for the slide transition.
func (b *SlideBuilder) WithTransitionSound(path string) *SlideBuilder {
	b.content = b.content.WithTransitionSound(path)
	return b
}

// WithTwoColumnLayout sets the layout to two_column.
func (b *SlideBuilder) WithTwoColumnLayout() *SlideBuilder {
	b.content = b.content.WithTwoColumnLayout()
	return b
}
