// Code generated by cmd/gen_slide_builder. DO NOT EDIT.

package elements

import (
	"github.com/djinn-soul/gopptx/pkg/pptx/charts"
	"github.com/djinn-soul/gopptx/pkg/pptx/shapes"
	"github.com/djinn-soul/gopptx/pkg/pptx/tables"
	"github.com/djinn-soul/gopptx/pkg/pptx/transitions"
)

// WithDefaultBulletStyle sets the base style for new bullets.
func (b *SlideBuilder) WithDefaultBulletStyle(style ParagraphStyle) *SlideBuilder {
	b.content = b.content.WithDefaultBulletStyle(style)
	return b
}

// WithDoughnutChart sets one doughnut chart for the slide.
func (b *SlideBuilder) WithDoughnutChart(chart charts.DoughnutChart) *SlideBuilder {
	b.content = b.content.WithDoughnutChart(chart)
	return b
}

// WithGradientBackground sets a gradient background for the slide.
func (b *SlideBuilder) WithGradientBackground(gradient shapes.ShapeGradientFill) *SlideBuilder {
	b.content = b.content.WithGradientBackground(gradient)
	return b
}

// WithLayout sets the slide layout (supports canonical and compatibility aliases).
func (b *SlideBuilder) WithLayout(layout string) *SlideBuilder {
	b.content = b.content.WithLayout(layout)
	return b
}

// WithLineChart sets one line chart for the slide.
func (b *SlideBuilder) WithLineChart(chart charts.LineChart) *SlideBuilder {
	b.content = b.content.WithLineChart(chart)
	return b
}

// WithLineMarkersChart calls SlideContent.WithLineMarkersChart on the wrapped slide.
func (b *SlideBuilder) WithLineMarkersChart(chart charts.LineMarkersChart) *SlideBuilder {
	b.content = b.content.WithLineMarkersChart(chart)
	return b
}

// WithLineStackedChart calls SlideContent.WithLineStackedChart on the wrapped slide.
func (b *SlideBuilder) WithLineStackedChart(chart charts.LineStackedChart) *SlideBuilder {
	b.content = b.content.WithLineStackedChart(chart)
	return b
}

// WithMorphTransition sets a Morph transition using PowerPoint's default mode.
func (b *SlideBuilder) WithMorphTransition() *SlideBuilder {
	b.content = b.content.WithMorphTransition()
	return b
}

// WithMorphTransitionOptions sets a Morph transition with explicit options.
func (b *SlideBuilder) WithMorphTransitionOptions(option transitions.MorphOption) *SlideBuilder {
	b.content = b.content.WithMorphTransitionOptions(option)
	return b
}

// WithNotes sets the speaker notes for the slide.
func (b *SlideBuilder) WithNotes(notes string) *SlideBuilder {
	b.content = b.content.WithNotes(notes)
	return b
}

// WithPictureBackground sets a picture background for the slide using image data.
func (b *SlideBuilder) WithPictureBackground(img shapes.Image) *SlideBuilder {
	b.content = b.content.WithPictureBackground(img)
	return b
}

// WithPie3DChart sets one 3D pie chart for the slide.
func (b *SlideBuilder) WithPie3DChart(chart charts.Pie3DChart) *SlideBuilder {
	b.content = b.content.WithPie3DChart(chart)
	return b
}

// WithPieChart sets one pie chart for the slide.
func (b *SlideBuilder) WithPieChart(chart charts.PieChart) *SlideBuilder {
	b.content = b.content.WithPieChart(chart)
	return b
}

// WithPlaceholderChart overrides a placeholder with a chart using the default placeholder type.
func (b *SlideBuilder) WithPlaceholderChart(index int, chart ChartDefinition) *SlideBuilder {
	b.content = b.content.WithPlaceholderChart(index, chart)
	return b
}

// WithPlaceholderChartAs overrides a placeholder with a chart and explicit placeholder type.
func (b *SlideBuilder) WithPlaceholderChartAs(index int, placeholderType string, chart ChartDefinition) *SlideBuilder {
	b.content = b.content.WithPlaceholderChartAs(index, placeholderType, chart)
	return b
}

// WithPlaceholderImage overrides a placeholder with an image using the default placeholder type.
func (b *SlideBuilder) WithPlaceholderImage(index int, img shapes.Image) *SlideBuilder {
	b.content = b.content.WithPlaceholderImage(index, img)
	return b
}

// WithPlaceholderImageAs overrides a placeholder with an image and explicit placeholder type.
func (b *SlideBuilder) WithPlaceholderImageAs(index int, placeholderType string, img shapes.Image) *SlideBuilder {
	b.content = b.content.WithPlaceholderImageAs(index, placeholderType, img)
	return b
}

// WithPlaceholderOverride adds custom geometry or style overrides to a placeholder.
func (b *SlideBuilder) WithPlaceholderOverride(target shapes.PlaceholderTarget, options shapes.PlaceholderOverrideOptions) *SlideBuilder {
	b.content = b.content.WithPlaceholderOverride(target, options)
	return b
}

// WithPlaceholderTable overrides a placeholder with a table using the default placeholder type.
func (b *SlideBuilder) WithPlaceholderTable(index int, table tables.Table) *SlideBuilder {
	b.content = b.content.WithPlaceholderTable(index, table)
	return b
}

// WithPlaceholderTableAs overrides a placeholder with a table and explicit placeholder type.
func (b *SlideBuilder) WithPlaceholderTableAs(index int, placeholderType string, table tables.Table) *SlideBuilder {
	b.content = b.content.WithPlaceholderTableAs(index, placeholderType, table)
	return b
}

// WithPlaceholderText overrides a placeholder with text using the default placeholder type.
func (b *SlideBuilder) WithPlaceholderText(index int, text string) *SlideBuilder {
	b.content = b.content.WithPlaceholderText(index, text)
	return b
}

// WithPlaceholderTextAs overrides a placeholder with text and explicit placeholder type.
func (b *SlideBuilder) WithPlaceholderTextAs(index int, placeholderType, text string) *SlideBuilder {
	b.content = b.content.WithPlaceholderTextAs(index, placeholderType, text)
	return b
}

// WithRadarChart calls SlideContent.WithRadarChart on the wrapped slide.
func (b *SlideBuilder) WithRadarChart(chart charts.RadarChart) *SlideBuilder {
	b.content = b.content.WithRadarChart(chart)
	return b
}

// WithRadarFilledChart calls SlideContent.WithRadarFilledChart on the wrapped slide.
func (b *SlideBuilder) WithRadarFilledChart(chart charts.RadarFilledChart) *SlideBuilder {
	b.content = b.content.WithRadarFilledChart(chart)
	return b
}

// WithRichNotes sets the speaker notes using rich text paragraphs.
func (b *SlideBuilder) WithRichNotes(body []Paragraph) *SlideBuilder {
	b.content = b.content.WithRichNotes(body)
	return b
}

// WithScatterChart sets one scatter chart for the slide.
func (b *SlideBuilder) WithScatterChart(chart charts.ScatterChart) *SlideBuilder {
	b.content = b.content.WithScatterChart(chart)
	return b
}

// WithSlideNumber enables or disables slide number display.
func (b *SlideBuilder) WithSlideNumber(show bool) *SlideBuilder {
	b.content = b.content.WithSlideNumber(show)
	return b
}

// WithStockHLCChart calls SlideContent.WithStockHLCChart on the wrapped slide.
func (b *SlideBuilder) WithStockHLCChart(chart charts.StockHLCChart) *SlideBuilder {
	b.content = b.content.WithStockHLCChart(chart)
	return b
}

// WithStockOHLCChart calls SlideContent.WithStockOHLCChart on the wrapped slide.
func (b *SlideBuilder) WithStockOHLCChart(chart charts.StockOHLCChart) *SlideBuilder {
	b.content = b.content.WithStockOHLCChart(chart)
	return b
}

// WithTable sets the table for the slide.
func (b *SlideBuilder) WithTable(t tables.Table) *SlideBuilder {
	b.content = b.content.WithTable(t)
	return b
}

// WithTitleAlign sets the horizontal alignment of the title (l|ctr|r|just).
func (b *SlideBuilder) WithTitleAlign(align string) *SlideBuilder {
	b.content = b.content.WithTitleAlign(align)
	return b
}

// WithTitleAndBigContentLayout sets the layout to title_and_big_content.
func (b *SlideBuilder) WithTitleAndBigContentLayout() *SlideBuilder {
	b.content = b.content.WithTitleAndBigContentLayout()
	return b
}

// WithTitleAndContentLayout sets the layout to title_and_content.
func (b *SlideBuilder) WithTitleAndContentLayout() *SlideBuilder {
	b.content = b.content.WithTitleAndContentLayout()
	return b
}

// WithTitleBold sets whether the title is bold.
func (b *SlideBuilder) WithTitleBold(bold bool) *SlideBuilder {
	b.content = b.content.WithTitleBold(bold)
	return b
}

// WithTitleColor sets the title color as RGB hex.
func (b *SlideBuilder) WithTitleColor(color string) *SlideBuilder {
	b.content = b.content.WithTitleColor(color)
	return b
}

// WithTitleFont sets the typeface for the slide title (e.g., "Consolas").
func (b *SlideBuilder) WithTitleFont(font string) *SlideBuilder {
	b.content = b.content.WithTitleFont(font)
	return b
}

// WithTitleItalic sets whether the title is italic.
func (b *SlideBuilder) WithTitleItalic(italic bool) *SlideBuilder {
	b.content = b.content.WithTitleItalic(italic)
	return b
}

// WithTitleOnlyLayout sets the layout to title_only.
func (b *SlideBuilder) WithTitleOnlyLayout() *SlideBuilder {
	b.content = b.content.WithTitleOnlyLayout()
	return b
}

// WithTitleSize sets the title font size in points.
func (b *SlideBuilder) WithTitleSize(size int) *SlideBuilder {
	b.content = b.content.WithTitleSize(size)
	return b
}

// WithTitleUnderline sets whether the title is underlined.
func (b *SlideBuilder) WithTitleUnderline(underline bool) *SlideBuilder {
	b.content = b.content.WithTitleUnderline(underline)
	return b
}
