// Code generated by cmd/gen_slide_builder. DO NOT EDIT.

package elements

import (
	"github.com/djinn-soul/gopptx/pkg/pptx/animations"
	"github.com/djinn-soul/gopptx/pkg/pptx/charts"
	"github.com/djinn-soul/gopptx/pkg/pptx/shapes"
	"github.com/djinn-soul/gopptx/pkg/pptx/smartart"
)

// AddAnimation adds an animation to the slide.
func (b *SlideBuilder) AddAnimation(anim animations.AnimationDefinition) *SlideBuilder {
	b.content = b.content.AddAnimation(anim)
	return b
}

// AddBullet appends one bullet item and returns the updated slide.
func (b *SlideBuilder) AddBullet(text string) *SlideBuilder {
	b.content = b.content.AddBullet(text)
	return b
}

// AddBulletRuns appends one bullet item with rich text runs.
func (b *SlideBuilder) AddBulletRuns(runs []Run) *SlideBuilder {
	b.content = b.content.AddBulletRuns(runs)
	return b
}

// AddBulletRunsWithStyle appends one bullet item with rich text runs and paragraph styling.
func (b *SlideBuilder) AddBulletRunsWithStyle(runs []Run, style ParagraphStyle) *SlideBuilder {
	b.content = b.content.AddBulletRunsWithStyle(runs, style)
	return b
}

// AddBulletWithStyle appends one bullet item with explicit styling.
func (b *SlideBuilder) AddBulletWithStyle(text string, style ParagraphStyle) *SlideBuilder {
	b.content = b.content.AddBulletWithStyle(text, style)
	return b
}

// AddCodeBlock appends a code block to the slide.
func (b *SlideBuilder) AddCodeBlock(block CodeBlock) *SlideBuilder {
	b.content = b.content.AddCodeBlock(block)
	return b
}

// AddComment appends a comment from the specified author.
func (b *SlideBuilder) AddComment(authorName, text string) *SlideBuilder {
	b.content = b.content.AddComment(authorName, text)
	return b
}

// AddConnector adds a connector to the slide.
func (b *SlideBuilder) AddConnector(connector shapes.Connector) *SlideBuilder {
	b.content = b.content.AddConnector(connector)
	return b
}

// AddFormattedBullet appends one bullet, reading **bold**, *italic* and `code`
func (b *SlideBuilder) AddFormattedBullet(text string) *SlideBuilder {
	b.content = b.content.AddFormattedBullet(text)
	return b
}

// AddFormattedBulletWithStyle is AddFormattedBullet with explicit paragraph
func (b *SlideBuilder) AddFormattedBulletWithStyle(text string, style ParagraphStyle) *SlideBuilder {
	b.content = b.content.AddFormattedBulletWithStyle(text, style)
	return b
}

// AddImage adds an image to the slide.
func (b *SlideBuilder) AddImage(img shapes.Image) *SlideBuilder {
	b.content = b.content.AddImage(img)
	return b
}

// AddLettered appends one lettered bullet item.
func (b *SlideBuilder) AddLettered(text string) *SlideBuilder {
	b.content = b.content.AddLettered(text)
	return b
}

// AddNoteBullet appends a bulleted paragraph to the speaker notes.
func (b *SlideBuilder) AddNoteBullet(text string) *SlideBuilder {
	b.content = b.content.AddNoteBullet(text)
	return b
}

// AddNoteNumbered appends a numbered paragraph to the speaker notes.
func (b *SlideBuilder) AddNoteNumbered(text string) *SlideBuilder {
	b.content = b.content.AddNoteNumbered(text)
	return b
}

// AddNoteParagraph appends a rich text paragraph to the speaker notes.
func (b *SlideBuilder) AddNoteParagraph(p Paragraph) *SlideBuilder {
	b.content = b.content.AddNoteParagraph(p)
	return b
}

// AddNoteSubBullet appends an indented bullet paragraph to the speaker notes.
func (b *SlideBuilder) AddNoteSubBullet(level int, text string) *SlideBuilder {
	b.content = b.content.AddNoteSubBullet(level, text)
	return b
}

// AddNumbered appends one numbered bullet item.
func (b *SlideBuilder) AddNumbered(text string) *SlideBuilder {
	b.content = b.content.AddNumbered(text)
	return b
}

// AddShape appends one shape and returns the updated slide content.
func (b *SlideBuilder) AddShape(sd shapes.ShapeDefinition) *SlideBuilder {
	b.content = b.content.AddShape(sd)
	return b
}

// AddSmartArt adds a SmartArt diagram to the slide.
func (b *SlideBuilder) AddSmartArt(sa smartart.SmartArt) *SlideBuilder {
	b.content = b.content.AddSmartArt(sa)
	return b
}

// AddSubBullet adds a bullet at level index 1..8.
func (b *SlideBuilder) AddSubBullet(level int, text string) *SlideBuilder {
	b.content = b.content.AddSubBullet(level, text)
	return b
}

// AutoRerouteConnectors recalculates connector sites from current shape positions.
func (b *SlideBuilder) AutoRerouteConnectors() *SlideBuilder {
	b.content = b.content.AutoRerouteConnectors()
	return b
}

// WithAreaChart sets one area chart for the slide.
func (b *SlideBuilder) WithAreaChart(chart charts.AreaChart) *SlideBuilder {
	b.content = b.content.WithAreaChart(chart)
	return b
}

// WithAreaStacked100Chart calls SlideContent.WithAreaStacked100Chart on the wrapped slide.
func (b *SlideBuilder) WithAreaStacked100Chart(chart charts.AreaStacked100Chart) *SlideBuilder {
	b.content = b.content.WithAreaStacked100Chart(chart)
	return b
}

// WithAreaStackedChart calls SlideContent.WithAreaStackedChart on the wrapped slide.
func (b *SlideBuilder) WithAreaStackedChart(chart charts.AreaStackedChart) *SlideBuilder {
	b.content = b.content.WithAreaStackedChart(chart)
	return b
}

// WithBackground sets a complex background for the slide.
func (b *SlideBuilder) WithBackground(bg SlideBackground) *SlideBuilder {
	b.content = b.content.WithBackground(bg)
	return b
}

// WithBackgroundColor sets the slide background as RGB hex.
func (b *SlideBuilder) WithBackgroundColor(color string) *SlideBuilder {
	b.content = b.content.WithBackgroundColor(color)
	return b
}

// WithBarChart sets one bar chart for the slide.
func (b *SlideBuilder) WithBarChart(chart charts.BarChart) *SlideBuilder {
	b.content = b.content.WithBarChart(chart)
	return b
}

// WithBarHorizontalChart calls SlideContent.WithBarHorizontalChart on the wrapped slide.
func (b *SlideBuilder) WithBarHorizontalChart(chart charts.BarHorizontalChart) *SlideBuilder {
	b.content = b.content.WithBarHorizontalChart(chart)
	return b
}

// WithBarStacked100Chart calls SlideContent.WithBarStacked100Chart on the wrapped slide.
func (b *SlideBuilder) WithBarStacked100Chart(chart charts.BarStacked100Chart) *SlideBuilder {
	b.content = b.content.WithBarStacked100Chart(chart)
	return b
}

// WithBarStackedChart calls SlideContent.WithBarStackedChart on the wrapped slide.
func (b *SlideBuilder) WithBarStackedChart(chart charts.BarStackedChart) *SlideBuilder {
	b.content = b.content.WithBarStackedChart(chart)
	return b
}

// WithBlankLayout sets the layout to blank.
func (b *SlideBuilder) WithBlankLayout() *SlideBuilder {
	b.content = b.content.WithBlankLayout()
	return b
}

// WithBubbleChart calls SlideContent.WithBubbleChart on the wrapped slide.
func (b *SlideBuilder) WithBubbleChart(chart charts.BubbleChart) *SlideBuilder {
	b.content = b.content.WithBubbleChart(chart)
	return b
}

// WithBulletStyle sets the bullet style for all bullets on this slide.
func (b *SlideBuilder) WithBulletStyle(style ParagraphStyle) *SlideBuilder {
	b.content = b.content.WithBulletStyle(style)
	return b
}

// WithBulletStyleName sets primary bullet style by name (e.g. BulletStyleNumber).
func (b *SlideBuilder) WithBulletStyleName(styleName string) *SlideBuilder {
	b.content = b.content.WithBulletStyleName(styleName)
	return b
}

// WithCenteredTitleLayout sets the layout to centered_title.
func (b *SlideBuilder) WithCenteredTitleLayout() *SlideBuilder {
	b.content = b.content.WithCenteredTitleLayout()
	return b
}

// WithChart sets any chart on the slide, replacing a chart already set. It is
func (b *SlideBuilder) WithChart(chart charts.Chart) *SlideBuilder {
	b.content = b.content.WithChart(chart)
	return b
}

// WithComboChart calls SlideContent.WithComboChart on the wrapped slide.
func (b *SlideBuilder) WithComboChart(chart charts.ComboChart) *SlideBuilder {
	b.content = b.content.WithComboChart(chart)
	return b
}

// WithContentBold sets whether the content is bold.
func (b *SlideBuilder) WithContentBold(bold bool) *SlideBuilder {
	b.content = b.content.WithContentBold(bold)
	return b
}

// WithContentColor sets the content color as RGB hex.
func (b *SlideBuilder) WithContentColor(color string) *SlideBuilder {
	b.content = b.content.WithContentColor(color)
	return b
}

// WithContentItalic sets whether the content is italic.
func (b *SlideBuilder) WithContentItalic(italic bool) *SlideBuilder {
	b.content = b.content.WithContentItalic(italic)
	return b
}
