package main

import (
	"fmt"
	"strings"
)

const (
	pyNameBar       = "BAR"
	pyNameColumn    = "COLUMN"
	pyNameStockOHLC = "STOCK_OHLC"
)

//nolint:gochecknoglobals // immutable generator configuration
var precedingAliases = map[string][]string{
	pyNameBar: {pyNameColumn},
}

//nolint:gochecknoglobals // immutable generator configuration
var aliasDoc = map[string]string{
	pyNameColumn: "Column/vertical bar chart. python-pptx spelling of BAR.",
}

//nolint:gochecknoglobals // immutable generator configuration
var memberDoc = map[string]string{
	pyNameBar:          "Vertical bar chart.",
	"BAR_HORIZONTAL":   "Horizontal bar chart.",
	"BAR_STACKED":      "Stacked bar chart.",
	"BAR_STACKED_100":  "100% stacked bar chart.",
	"LINE":             "Line chart.",
	"LINE_MARKERS":     "Line chart with markers.",
	"LINE_STACKED":     "Stacked line chart.",
	"SCATTER":          "Scatter/XY chart. Takes x and y values, not categories.",
	"AREA":             "Area chart.",
	"AREA_STACKED":     "Stacked area chart.",
	"AREA_STACKED_100": "100% stacked area chart.",
	"PIE":              "Pie chart.",
	"DOUGHNUT":         "Doughnut chart.",
	"BUBBLE":           "Bubble chart. Takes x, y and size values, not categories.",
	"RADAR":            "Radar chart.",
	"RADAR_FILLED":     "Filled radar chart.",
	"STOCK_HLC":        "Stock high-low-close chart.",
	pyNameStockOHLC:    "Stock open-high-low-close chart.",
	"COMBO":            "Combo chart: bar and line series on one category axis.",
}

func renderPython(types []chartType) string {
	var out strings.Builder
	out.WriteString(pythonHeader)
	for _, chart := range types {
		aliases := precedingAliases[chart.PyName]
		for _, alias := range aliases {
			writeMember(&out, alias, chart.Value, aliasDoc[alias], "", false)
		}
		writeMember(
			&out, chart.PyName, chart.Value, memberDoc[chart.PyName],
			chart.GoName, len(aliases) > 0,
		)
	}
	out.WriteString(pythonMethods)
	return out.String()
}

func writeMember(
	out *strings.Builder,
	name string,
	value string,
	doc string,
	goName string,
	isAliasOf bool,
) {
	if isAliasOf {
		fmt.Fprintf(out, "    %s = %q  # noqa: PIE796\n", name, value)
	} else {
		fmt.Fprintf(out, "    %s = %q\n", name, value)
	}
	if doc == "" {
		doc = name + " chart."
	}
	if goName != "" {
		fmt.Fprintf(out, "    \"\"\"%s Go: enums.%s.\"\"\"\n\n", doc, goName)
		return
	}
	fmt.Fprintf(out, "    \"\"\"%s\"\"\"\n\n", doc)
}

const pythonHeader = `"""Chart type constants for PowerPoint chart operations.

GENERATED FILE - DO NOT EDIT.

Generated by cmd/gen_chart_types from the XLChartType constants in
pkg/pptx/enums/shape_chart.go. Change the Go constants and re-run
"go generate ./..." rather than editing this file.
"""

from __future__ import annotations

from enum import Enum

__all__ = ["ChartType"]


class ChartType(str, Enum):
    """Chart types accepted by add_chart and friends.

    Members subclass str, so a member compares equal to and serializes as its
    wire value: ChartType.PIE == "pie" is True. Passing the bare string works
    too; the members exist so the set of valid values is discoverable, checkable
    by a type checker, and typo-proof.

    Examples:
        slide.add_chart(
            ChartType.PIE,
            ["A", "B", "C"],
            [25.0, 35.0, 40.0],
            title="Sales Mix",
            bounds=(Inches(1), Inches(1), Inches(4), Inches(3)),
        )
    """

`

const pythonMethods = `    # Report the wire value from str(), matching enum.StrEnum on Python 3.11+.
    # gopptx supports Python 3.10, where StrEnum does not exist.
    __str__ = str.__str__

    @classmethod
    def get_all(cls) -> dict[str, str]:
        """Map every member name, aliases included, to its wire value.

        Returns:
            Dictionary of constant name to chart type value.
        """
        return {name: member.value for name, member in cls.__members__.items()}

    @classmethod
    def values(cls) -> frozenset[str]:
        """Return the distinct wire values, without alias duplicates."""
        return frozenset(member.value for member in cls)

    @classmethod
    def validate(cls, chart_type: str | None) -> str:
        """Check a chart type and return it as a plain string.

        Accepts a ChartType member or its wire value (they are equal). Member
        *names* such as "COLUMN" are not values and are rejected.

        Args:
            chart_type: A ChartType member or wire value such as "pie".

        Returns:
            The wire value.

        Raises:
            ValueError: If chart_type is empty or not a known value.

        Examples:
            ChartType.validate(ChartType.COLUMN)   # -> "bar"
            ChartType.validate("pie")              # -> "pie"
            ChartType.validate("COLUMN")           # -> ValueError
        """
        if not chart_type:
            raise ValueError("chart_type cannot be empty")
        if chart_type in cls.values():
            return str(chart_type)
        valid_values = ", ".join(sorted(cls.values()))
        raise ValueError(" ".join((
            f"Invalid chart_type {chart_type!r}.",
            "Use a ChartType member such as ChartType.COLUMN or ChartType.PIE.",
            f"Valid values: {valid_values}",
        )))

    @classmethod
    def get_by_name(cls, name: str) -> str | None:
        """Look up a wire value by member name, case-sensitively.

        Args:
            name: Constant name such as "COLUMN", "PIE" or "LINE_MARKERS".

        Returns:
            The wire value, or None when no member has that name.
        """
        member = cls.__members__.get(name)
        return None if member is None else member.value
`
