// Code generated by gen_smartart_layouts. DO NOT EDIT.

package smartart

// The layouts PowerPoint offers, named as its gallery names them.
const (
	// VerticalBracketList is PowerPoint's "Vertical Bracket List" layout.
	VerticalBracketList Layout = "urn:diagrams.loki3.com/BracketList"
	// TabbedArc is PowerPoint's "Tabbed Arc" layout.
	TabbedArc Layout = "urn:diagrams.loki3.com/TabbedArc+Icon"
	// VaryingWidthList is PowerPoint's "Varying Width List" layout.
	VaryingWidthList Layout = "urn:diagrams.loki3.com/VaryingWidthList"
	// StepDownProcess is PowerPoint's "Step Down Process" layout.
	StepDownProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/StepDownProcess"
	// ArchitectureLayout is PowerPoint's "Architecture Layout" layout.
	ArchitectureLayout Layout = "urn:microsoft.com/office/officeart/2005/8/layout/architecture"
	// DivergingArrows is PowerPoint's "Diverging Arrows" layout.
	DivergingArrows Layout = "urn:microsoft.com/office/officeart/2005/8/layout/arrow1"
	// UpwardArrow is PowerPoint's "Upward Arrow" layout.
	UpwardArrow Layout = "urn:microsoft.com/office/officeart/2005/8/layout/arrow2"
	// CounterbalanceArrows is PowerPoint's "Counterbalance Arrows" layout.
	CounterbalanceArrows Layout = "urn:microsoft.com/office/officeart/2005/8/layout/arrow3"
	// OpposingArrows is PowerPoint's "Opposing Arrows" layout.
	OpposingArrows Layout = "urn:microsoft.com/office/officeart/2005/8/layout/arrow4"
	// ConvergingArrows is PowerPoint's "Converging Arrows" layout.
	ConvergingArrows Layout = "urn:microsoft.com/office/officeart/2005/8/layout/arrow5"
	// ArrowRibbon is PowerPoint's "Arrow Ribbon" layout.
	ArrowRibbon Layout = "urn:microsoft.com/office/officeart/2005/8/layout/arrow6"
	// BendingPictureAccentList is PowerPoint's "Bending Picture Accent List" layout.
	BendingPictureAccentList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/bList2"
	// CircularBendingProcess is PowerPoint's "Circular Bending Process" layout.
	CircularBendingProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/bProcess2"
	// RepeatingBendingProcess is PowerPoint's "Repeating Bending Process" layout.
	RepeatingBendingProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/bProcess3"
	// VerticalBendingProcess is PowerPoint's "Vertical Bending Process" layout.
	VerticalBendingProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/bProcess4"
	// Balance is PowerPoint's "Balance" layout.
	Balance Layout = "urn:microsoft.com/office/officeart/2005/8/layout/balance1"
	// BasicPie is PowerPoint's "Basic Pie" layout.
	BasicPie Layout = "urn:microsoft.com/office/officeart/2005/8/layout/chart3"
	// BasicChevronProcess is PowerPoint's "Basic Chevron Process" layout.
	BasicChevronProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/chevron1"
	// VerticalChevronList is PowerPoint's "Vertical Chevron List" layout.
	VerticalChevronList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/chevron2"
	// ChevronAccentProcess is PowerPoint's "Chevron Accent Process" layout.
	ChevronAccentProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/chevronAccent+Icon"
	// ContinuousCycle is PowerPoint's "Continuous Cycle" layout.
	ContinuousCycle Layout = "urn:microsoft.com/office/officeart/2005/8/layout/cycle3"
	// CycleMatrix is PowerPoint's "Cycle Matrix" layout.
	CycleMatrix Layout = "urn:microsoft.com/office/officeart/2005/8/layout/cycle4"
	// NondirectionalCycle is PowerPoint's "Nondirectional Cycle" layout.
	NondirectionalCycle Layout = "urn:microsoft.com/office/officeart/2005/8/layout/cycle6"
	// MultidirectionalCycle is PowerPoint's "Multidirectional Cycle" layout.
	MultidirectionalCycle Layout = "urn:microsoft.com/office/officeart/2005/8/layout/cycle7"
	// SegmentedCycle is PowerPoint's "Segmented Cycle" layout.
	SegmentedCycle Layout = "urn:microsoft.com/office/officeart/2005/8/layout/cycle8"
	// Equation is PowerPoint's "Equation" layout.
	Equation Layout = "urn:microsoft.com/office/officeart/2005/8/layout/equation1"
	// VerticalEquation is PowerPoint's "Vertical Equation" layout.
	VerticalEquation Layout = "urn:microsoft.com/office/officeart/2005/8/layout/equation2"
	// Funnel is PowerPoint's "Funnel" layout.
	Funnel Layout = "urn:microsoft.com/office/officeart/2005/8/layout/funnel1"
	// Gear is PowerPoint's "Gear" layout.
	Gear Layout = "urn:microsoft.com/office/officeart/2005/8/layout/gear1"
	// ClosedChevronProcess is PowerPoint's "Closed Chevron Process" layout.
	ClosedChevronProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hChevron3"
	// TableList is PowerPoint's "Table List" layout.
	TableList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hList3"
	// TrapezoidList is PowerPoint's "Trapezoid List" layout.
	TrapezoidList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hList6"
	// ContinuousPictureList is PowerPoint's "Continuous Picture List" layout.
	ContinuousPictureList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hList7"
	// StackedList is PowerPoint's "Stacked List" layout.
	StackedList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hList9"
	// PictureAccentProcess is PowerPoint's "Picture Accent Process" layout.
	PictureAccentProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hProcess10"
	// BasicTimeline is PowerPoint's "Basic Timeline" layout.
	BasicTimeline Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hProcess11"
	// ContinuousArrowProcess is PowerPoint's "Continuous Arrow Process" layout.
	ContinuousArrowProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hProcess3"
	// ProcessArrows is PowerPoint's "Process Arrows" layout.
	ProcessArrows Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hProcess6"
	// DetailedProcess is PowerPoint's "Detailed Process" layout.
	DetailedProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hProcess7"
	// HierarchyList is PowerPoint's "Hierarchy List" layout.
	HierarchyList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hierarchy3"
	// TableHierarchy is PowerPoint's "Table Hierarchy" layout.
	TableHierarchy Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hierarchy4"
	// HorizontalLabeledHierarchy is PowerPoint's "Horizontal Labeled Hierarchy" layout.
	HorizontalLabeledHierarchy Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hierarchy5"
	// LabeledHierarchy is PowerPoint's "Labeled Hierarchy" layout.
	LabeledHierarchy Layout = "urn:microsoft.com/office/officeart/2005/8/layout/hierarchy6"
	// ProcessList is PowerPoint's "Process List" layout.
	ProcessList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/lProcess1"
	// GroupedList is PowerPoint's "Grouped List" layout.
	GroupedList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/lProcess2"
	// ChevronList is PowerPoint's "Chevron List" layout.
	ChevronList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/lProcess3"
	// VerticalBoxList is PowerPoint's "Vertical Box List" layout.
	VerticalBoxList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/list1"
	// GridMatrix is PowerPoint's "Grid Matrix" layout.
	GridMatrix Layout = "urn:microsoft.com/office/officeart/2005/8/layout/matrix2"
	// PictureCaptionList is PowerPoint's "Picture Caption List" layout.
	PictureCaptionList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/pList1"
	// HorizontalPictureList is PowerPoint's "Horizontal Picture List" layout.
	HorizontalPictureList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/pList2"
	// PictureOrganizationChart is PowerPoint's "Picture Organization Chart" layout.
	PictureOrganizationChart Layout = "urn:microsoft.com/office/officeart/2005/8/layout/pictureOrgChart+Icon"
	// VerticalProcess is PowerPoint's "Vertical Process" layout.
	VerticalProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/process2"
	// SegmentedProcess is PowerPoint's "Segmented Process" layout.
	SegmentedProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/process4"
	// BasicBendingProcess is PowerPoint's "Basic Bending Process" layout.
	BasicBendingProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/process5"
	// PyramidList is PowerPoint's "Pyramid List" layout.
	PyramidList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/pyramid2"
	// SegmentedPyramid is PowerPoint's "Segmented Pyramid" layout.
	SegmentedPyramid Layout = "urn:microsoft.com/office/officeart/2005/8/layout/pyramid4"
	// RadialList is PowerPoint's "Radial List" layout.
	RadialList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/radial2"
	// RadialVenn is PowerPoint's "Radial Venn" layout.
	RadialVenn Layout = "urn:microsoft.com/office/officeart/2005/8/layout/radial3"
	// ConvergingRadial is PowerPoint's "Converging Radial" layout.
	ConvergingRadial Layout = "urn:microsoft.com/office/officeart/2005/8/layout/radial4"
	// DivergingRadial is PowerPoint's "Diverging Radial " layout.
	DivergingRadial Layout = "urn:microsoft.com/office/officeart/2005/8/layout/radial5"
	// RadialCycle is PowerPoint's "Radial Cycle" layout.
	RadialCycle Layout = "urn:microsoft.com/office/officeart/2005/8/layout/radial6"
	// InterconnectedRings is PowerPoint's "Interconnected Rings" layout.
	InterconnectedRings Layout = "urn:microsoft.com/office/officeart/2005/8/layout/rings+Icon"
	// BasicTarget is PowerPoint's "Basic Target" layout.
	BasicTarget Layout = "urn:microsoft.com/office/officeart/2005/8/layout/target1"
	// NestedTarget is PowerPoint's "Nested Target" layout.
	NestedTarget Layout = "urn:microsoft.com/office/officeart/2005/8/layout/target2"
	// TargetList is PowerPoint's "Target List" layout.
	TargetList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/target3"
	// VerticalBulletList is PowerPoint's "Vertical Bullet List" layout.
	VerticalBulletList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/vList2"
	// VerticalPictureAccentList is PowerPoint's "Vertical Picture Accent List" layout.
	VerticalPictureAccentList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/vList3"
	// VerticalPictureList is PowerPoint's "Vertical Picture List" layout.
	VerticalPictureList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/vList4"
	// VerticalArrowList is PowerPoint's "Vertical Arrow List" layout.
	VerticalArrowList Layout = "urn:microsoft.com/office/officeart/2005/8/layout/vList6"
	// StaggeredProcess is PowerPoint's "Staggered Process" layout.
	StaggeredProcess Layout = "urn:microsoft.com/office/officeart/2005/8/layout/vProcess5"
	// AccentedPicture is PowerPoint's "Accented Picture" layout.
	AccentedPicture Layout = "urn:microsoft.com/office/officeart/2008/layout/AccentedPicture"
	// AlternatingHexagons is PowerPoint's "Alternating Hexagons" layout.
	AlternatingHexagons Layout = "urn:microsoft.com/office/officeart/2008/layout/AlternatingHexagons"
	// AlternatingPictureBlocks is PowerPoint's "Alternating Picture Blocks" layout.
	AlternatingPictureBlocks Layout = "urn:microsoft.com/office/officeart/2008/layout/AlternatingPictureBlocks"
	// AlternatingPictureCircles is PowerPoint's "Alternating Picture Circles" layout.
	AlternatingPictureCircles Layout = "urn:microsoft.com/office/officeart/2008/layout/AlternatingPictureCircles"
	// AscendingPictureAccentProcess is PowerPoint's "Ascending Picture Accent Process" layout.
	AscendingPictureAccentProcess Layout = "urn:microsoft.com/office/officeart/2008/layout/AscendingPictureAccentProcess"
	// BendingPictureBlocks is PowerPoint's "Bending Picture Blocks" layout.
	BendingPictureBlocks Layout = "urn:microsoft.com/office/officeart/2008/layout/BendingPictureBlocks"
	// BendingPictureCaption is PowerPoint's "Bending Picture Caption" layout.
	BendingPictureCaption Layout = "urn:microsoft.com/office/officeart/2008/layout/BendingPictureCaption"
	// BendingPictureCaptionList is PowerPoint's "Bending Picture Caption List" layout.
	BendingPictureCaptionList Layout = "urn:microsoft.com/office/officeart/2008/layout/BendingPictureCaptionList"
	// BendingPictureSemiTransparentText is PowerPoint's "Bending Picture Semi-Transparent Text" layout.
	BendingPictureSemiTransparentText Layout = "urn:microsoft.com/office/officeart/2008/layout/BendingPictureSemiTransparentText"
	// BubblePictureList is PowerPoint's "Bubble Picture List" layout.
	BubblePictureList Layout = "urn:microsoft.com/office/officeart/2008/layout/BubblePictureList"
	// CaptionedPictures is PowerPoint's "Captioned Pictures" layout.
	CaptionedPictures Layout = "urn:microsoft.com/office/officeart/2008/layout/CaptionedPictures"
	// CircleAccentTimeline is PowerPoint's "Circle Accent Timeline" layout.
	CircleAccentTimeline Layout = "urn:microsoft.com/office/officeart/2008/layout/CircleAccentTimeline"
	// CircularPictureCallout is PowerPoint's "Circular Picture Callout" layout.
	CircularPictureCallout Layout = "urn:microsoft.com/office/officeart/2008/layout/CircularPictureCallout"
	// HalfCircleOrganizationChart is PowerPoint's "Half Circle Organization Chart" layout.
	HalfCircleOrganizationChart Layout = "urn:microsoft.com/office/officeart/2008/layout/HalfCircleOrganizationChart"
	// HexagonCluster is PowerPoint's "Hexagon Cluster" layout.
	HexagonCluster Layout = "urn:microsoft.com/office/officeart/2008/layout/HexagonCluster"
	// HorizontalMultiLevelHierarchy is PowerPoint's "Horizontal Multi-Level Hierarchy" layout.
	HorizontalMultiLevelHierarchy Layout = "urn:microsoft.com/office/officeart/2008/layout/HorizontalMultiLevelHierarchy"
	// IncreasingCircleProcess is PowerPoint's "Increasing Circle Process" layout.
	IncreasingCircleProcess Layout = "urn:microsoft.com/office/officeart/2008/layout/IncreasingCircleProcess"
	// LinedList is PowerPoint's "Lined List" layout.
	LinedList Layout = "urn:microsoft.com/office/officeart/2008/layout/LinedList"
	// NameAndTitleOrganizationChart is PowerPoint's "Name and Title Organization Chart" layout.
	NameAndTitleOrganizationChart Layout = "urn:microsoft.com/office/officeart/2008/layout/NameandTitleOrganizationalChart"
	// PictureAccentBlocks is PowerPoint's "Picture Accent Blocks" layout.
	PictureAccentBlocks Layout = "urn:microsoft.com/office/officeart/2008/layout/PictureAccentBlocks"
	// TitledPictureAccentList is PowerPoint's "Titled Picture Accent List" layout.
	TitledPictureAccentList Layout = "urn:microsoft.com/office/officeart/2008/layout/PictureAccentList"
	// PictureLineup is PowerPoint's "Picture Lineup" layout.
	PictureLineup Layout = "urn:microsoft.com/office/officeart/2008/layout/PictureLineup"
	// RadialCluster is PowerPoint's "Radial Cluster" layout.
	RadialCluster Layout = "urn:microsoft.com/office/officeart/2008/layout/RadialCluster"
	// TitlePictureLineup is PowerPoint's "Title Picture Lineup" layout.
	TitlePictureLineup Layout = "urn:microsoft.com/office/officeart/2008/layout/TitlePictureLineup"
	// TitledPictureBlocks is PowerPoint's "Titled Picture Blocks" layout.
	TitledPictureBlocks Layout = "urn:microsoft.com/office/officeart/2008/layout/TitledPictureBlocks"
	// VerticalAccentList is PowerPoint's "Vertical Accent List" layout.
	VerticalAccentList Layout = "urn:microsoft.com/office/officeart/2008/layout/VerticalAccentList"
	// VerticalCircleList is PowerPoint's "Vertical Circle List" layout.
	VerticalCircleList Layout = "urn:microsoft.com/office/officeart/2008/layout/VerticalCircleList"
	// VerticalCurvedList is PowerPoint's "Vertical Curved List" layout.
	VerticalCurvedList Layout = "urn:microsoft.com/office/officeart/2008/layout/VerticalCurvedList"
	// DescendingBlockList is PowerPoint's "Descending Block List" layout.
	DescendingBlockList Layout = "urn:microsoft.com/office/officeart/2009/3/layout/BlockDescendingList"
	// CircleRelationship is PowerPoint's "Circle Relationship" layout.
	CircleRelationship Layout = "urn:microsoft.com/office/officeart/2009/3/layout/CircleRelationship"
	// DescendingProcess is PowerPoint's "Descending Process" layout.
	DescendingProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/DescendingProcess"
	// FramedTextPicture is PowerPoint's "Framed Text Picture" layout.
	FramedTextPicture Layout = "urn:microsoft.com/office/officeart/2009/3/layout/FramedTextPicture"
	// HorizontalOrganizationChart is PowerPoint's "Horizontal Organization Chart" layout.
	HorizontalOrganizationChart Layout = "urn:microsoft.com/office/officeart/2009/3/layout/HorizontalOrganizationChart"
	// IncreasingArrowsProcess is PowerPoint's "Increasing Arrows Process" layout.
	IncreasingArrowsProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/IncreasingArrowsProcess"
	// OpposingIdeas is PowerPoint's "Opposing Ideas" layout.
	OpposingIdeas Layout = "urn:microsoft.com/office/officeart/2009/3/layout/OpposingIdeas"
	// PhasedProcess is PowerPoint's "Phased Process" layout.
	PhasedProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/PhasedProcess"
	// PieProcess is PowerPoint's "Pie Process" layout.
	PieProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/PieProcess"
	// PlusAndMinus is PowerPoint's "Plus and Minus" layout.
	PlusAndMinus Layout = "urn:microsoft.com/office/officeart/2009/3/layout/PlusandMinus"
	// RandomToResultProcess is PowerPoint's "Random to Result Process" layout.
	RandomToResultProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/RandomtoResultProcess"
	// SnapshotPictureList is PowerPoint's "Snapshot Picture List" layout.
	SnapshotPictureList Layout = "urn:microsoft.com/office/officeart/2009/3/layout/SnapshotPictureList"
	// SpiralPicture is PowerPoint's "Spiral Picture" layout.
	SpiralPicture Layout = "urn:microsoft.com/office/officeart/2009/3/layout/SpiralPicture"
	// StepUpProcess is PowerPoint's "Step Up Process" layout.
	StepUpProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/StepUpProcess"
	// SubStepProcess is PowerPoint's "Sub-Step Process" layout.
	SubStepProcess Layout = "urn:microsoft.com/office/officeart/2009/3/layout/SubStepProcess"
	// CircleArrowProcess is PowerPoint's "Circle Arrow Process" layout.
	CircleArrowProcess Layout = "urn:microsoft.com/office/officeart/2009/layout/CircleArrowProcess"
	// CirclePictureHierarchy is PowerPoint's "Circle Picture Hierarchy" layout.
	CirclePictureHierarchy Layout = "urn:microsoft.com/office/officeart/2009/layout/CirclePictureHierarchy"
	// ReverseList is PowerPoint's "Reverse List" layout.
	ReverseList Layout = "urn:microsoft.com/office/officeart/2009/layout/ReverseList"
	// CircleProcess is PowerPoint's "Circle Process" layout.
	CircleProcess Layout = "urn:microsoft.com/office/officeart/2011/layout/CircleProcess"
	// ConvergingText is PowerPoint's "Converging Text" layout.
	ConvergingText Layout = "urn:microsoft.com/office/officeart/2011/layout/ConvergingText"
	// HexagonRadial is PowerPoint's "Hexagon Radial" layout.
	HexagonRadial Layout = "urn:microsoft.com/office/officeart/2011/layout/HexagonRadial"
	// InterconnectedBlockProcess is PowerPoint's "Interconnected Block Process" layout.
	InterconnectedBlockProcess Layout = "urn:microsoft.com/office/officeart/2011/layout/InterconnectedBlockProcess"
	// PictureFrame is PowerPoint's "Picture Frame" layout.
	PictureFrame Layout = "urn:microsoft.com/office/officeart/2011/layout/Picture Frame"
	// RadialPictureList is PowerPoint's "Radial Picture List" layout.
	RadialPictureList Layout = "urn:microsoft.com/office/officeart/2011/layout/RadialPictureList"
	// TabList is PowerPoint's "Tab List" layout.
	TabList Layout = "urn:microsoft.com/office/officeart/2011/layout/TabList"
	// ThemePictureAccent is PowerPoint's "Theme Picture Accent" layout.
	ThemePictureAccent Layout = "urn:microsoft.com/office/officeart/2011/layout/ThemePictureAccent"
	// ThemePictureAlternatingAccent is PowerPoint's "Theme Picture Alternating Accent" layout.
	ThemePictureAlternatingAccent Layout = "urn:microsoft.com/office/officeart/2011/layout/ThemePictureAlternatingAccent"
	// ThemePictureGrid is PowerPoint's "Theme Picture Grid" layout.
	ThemePictureGrid Layout = "urn:microsoft.com/office/officeart/2011/layout/ThemePictureGrid"
	// AlternatingCircleProcess is PowerPoint's "Alternating Circle Process" layout.
	AlternatingCircleProcess Layout = "urn:microsoft.com/office/officeart/2024/layout/AlternatingCircleProcess"
	// BulletTimeline is PowerPoint's "Bullet Timeline" layout.
	BulletTimeline Layout = "urn:microsoft.com/office/officeart/2024/layout/BulletTimeline"
	// BulletTimelineInverted is PowerPoint's "Bullet Timeline Inverted" layout.
	BulletTimelineInverted Layout = "urn:microsoft.com/office/officeart/2024/layout/BulletTimelineInverted"
	// HorizontalActionList is PowerPoint's "Horizontal Action List" layout.
	HorizontalActionList Layout = "urn:microsoft.com/office/officeart/2024/layout/HorizontalActionList"
	// IconCircleLabelList is PowerPoint's "Icon Circle Label List" layout.
	IconCircleLabelList Layout = "urn:microsoft.com/office/officeart/2024/layout/IconCircleLabelList"
	// MeetTheTeam is PowerPoint's "Meet The Team" layout.
	MeetTheTeam Layout = "urn:microsoft.com/office/officeart/2024/layout/MeetTheTeam"
	// MeetTheTeamCard is PowerPoint's "Meet The Team Card" layout.
	MeetTheTeamCard Layout = "urn:microsoft.com/office/officeart/2024/layout/MeetTheTeamCard"
	// MeetTheTeamCardVertical is PowerPoint's "Meet The Team Card Vertical" layout.
	MeetTheTeamCardVertical Layout = "urn:microsoft.com/office/officeart/2024/layout/MeetTheTeamCardVertical"
	// MeetTheTeamOval is PowerPoint's "Meet The Team Oval" layout.
	MeetTheTeamOval Layout = "urn:microsoft.com/office/officeart/2024/layout/MeetTheTeamOval"
	// NumberedLinearArrowProcess is PowerPoint's "Numbered Linear Arrow Process" layout.
	NumberedLinearArrowProcess Layout = "urn:microsoft.com/office/officeart/2024/layout/NumberedLinearArrowProcess"
	// NumberedCardList is PowerPoint's "Numbered Card List" layout.
	NumberedCardList Layout = "urn:microsoft.com/office/officeart/2024/layout/NumberedTitleCardList"
	// NumberedTitleList is PowerPoint's "Numbered Title List" layout.
	NumberedTitleList Layout = "urn:microsoft.com/office/officeart/2024/layout/NumberedTitleList"
	// VerticalActionList is PowerPoint's "Vertical Action List" layout.
	VerticalActionList Layout = "urn:microsoft.com/office/officeart/2024/layout/VerticalActionList"
	// NumberedDotsHorizontal is PowerPoint's "Numbered Dots Horizontal" layout.
	NumberedDotsHorizontal Layout = "urn:microsoft.com/office/officeart/2026/layout/NumberedDotsHorizontal"
	// NumberedDotsVertical is PowerPoint's "Numbered Dots Vertical" layout.
	NumberedDotsVertical Layout = "urn:microsoft.com/office/officeart/2026/layout/NumberedDotsVertical"
	// SmallDotsHorizontal is PowerPoint's "Small Dots Horizontal" layout.
	SmallDotsHorizontal Layout = "urn:microsoft.com/office/officeart/2026/layout/SmallDotsHorizontal"
	// SmallDotsVertical is PowerPoint's "Small Dots Vertical" layout.
	SmallDotsVertical Layout = "urn:microsoft.com/office/officeart/2026/layout/SmallDotsVertical"
	// TextCardShortLine is PowerPoint's "Text Card Short Line" layout.
	TextCardShortLine Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardShortLine"
	// TextCardShortLineNumber is PowerPoint's "Text Card Short Line Number" layout.
	TextCardShortLineNumber Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardShortLineNumber"
	// TextCardShortLineQuote is PowerPoint's "Text Card Short Line Quote" layout.
	TextCardShortLineQuote Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardShortLineQuote"
	// TextCardShortLineWide is PowerPoint's "Text Card Short Line Wide" layout.
	TextCardShortLineWide Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardShortLineWide"
	// TextCardSideLineIcon is PowerPoint's "Text Card Side Line Icon" layout.
	TextCardSideLineIcon Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardSideLineIcon"
	// TextCardSideLineNumbered is PowerPoint's "Text Card Side Line Numbered" layout.
	TextCardSideLineNumbered Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardSideLineNumbered"
	// TextCardSideLineQuote is PowerPoint's "Text Card Side Line Quote" layout.
	TextCardSideLineQuote Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardSideLineQuote"
	// TextCardSideLineWideImage is PowerPoint's "Text Card Side Line Wide Image" layout.
	TextCardSideLineWideImage Layout = "urn:microsoft.com/office/officeart/2026/layout/TextCardSideLineWideImage"
)
